run:
  timeout: 3m

linters:
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/InCrowd/unified-qual-api
