// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	qs "github.com/InCrowd/unified-qual-api/internal/repository/qs"
)

// MockQsRespondentRepository is an autogenerated mock type for the RespondentRepository type
type MockQsRespondentRepository struct {
	mock.Mock
}

type MockQsRespondentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQsRespondentRepository) EXPECT() *MockQsRespondentRepository_Expecter {
	return &MockQsRespondentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, r
func (_m *MockQsRespondentRepository) Create(ctx context.Context, r *qs.Respondent) (int64, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *qs.Respondent) (int64, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *qs.Respondent) int64); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *qs.Respondent) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockQsRespondentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *qs.Respondent
func (_e *MockQsRespondentRepository_Expecter) Create(ctx interface{}, r interface{}) *MockQsRespondentRepository_Create_Call {
	return &MockQsRespondentRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *MockQsRespondentRepository_Create_Call) Run(run func(ctx context.Context, r *qs.Respondent)) *MockQsRespondentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*qs.Respondent))
	})
	return _c
}

func (_c *MockQsRespondentRepository_Create_Call) Return(_a0 int64, _a1 error) *MockQsRespondentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_Create_Call) RunAndReturn(run func(context.Context, *qs.Respondent) (int64, error)) *MockQsRespondentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCommunicationAddress provides a mock function with given fields: ctx, responderID, transportTypeID, address
func (_m *MockQsRespondentRepository) CreateCommunicationAddress(ctx context.Context, responderID int64, transportTypeID int, address string) (int64, error) {
	ret := _m.Called(ctx, responderID, transportTypeID, address)

	if len(ret) == 0 {
		panic("no return value specified for CreateCommunicationAddress")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string) (int64, error)); ok {
		return rf(ctx, responderID, transportTypeID, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string) int64); ok {
		r0 = rf(ctx, responderID, transportTypeID, address)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, string) error); ok {
		r1 = rf(ctx, responderID, transportTypeID, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_CreateCommunicationAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCommunicationAddress'
type MockQsRespondentRepository_CreateCommunicationAddress_Call struct {
	*mock.Call
}

// CreateCommunicationAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - responderID int64
//   - transportTypeID int
//   - address string
func (_e *MockQsRespondentRepository_Expecter) CreateCommunicationAddress(ctx interface{}, responderID interface{}, transportTypeID interface{}, address interface{}) *MockQsRespondentRepository_CreateCommunicationAddress_Call {
	return &MockQsRespondentRepository_CreateCommunicationAddress_Call{Call: _e.mock.On("CreateCommunicationAddress", ctx, responderID, transportTypeID, address)}
}

func (_c *MockQsRespondentRepository_CreateCommunicationAddress_Call) Run(run func(ctx context.Context, responderID int64, transportTypeID int, address string)) *MockQsRespondentRepository_CreateCommunicationAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockQsRespondentRepository_CreateCommunicationAddress_Call) Return(_a0 int64, _a1 error) *MockQsRespondentRepository_CreateCommunicationAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_CreateCommunicationAddress_Call) RunAndReturn(run func(context.Context, int64, int, string) (int64, error)) *MockQsRespondentRepository_CreateCommunicationAddress_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRespondentMRA provides a mock function with given fields: ctx, firstName, lastName, title, extID, sessKey, tz, tzAbbr, lang
func (_m *MockQsRespondentRepository) CreateRespondentMRA(ctx context.Context, firstName string, lastName string, title string, extID string, sessKey string, tz string, tzAbbr string, lang string) (int64, error) {
	ret := _m.Called(ctx, firstName, lastName, title, extID, sessKey, tz, tzAbbr, lang)

	if len(ret) == 0 {
		panic("no return value specified for CreateRespondentMRA")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, string) (int64, error)); ok {
		return rf(ctx, firstName, lastName, title, extID, sessKey, tz, tzAbbr, lang)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, string) int64); ok {
		r0 = rf(ctx, firstName, lastName, title, extID, sessKey, tz, tzAbbr, lang)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, firstName, lastName, title, extID, sessKey, tz, tzAbbr, lang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_CreateRespondentMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRespondentMRA'
type MockQsRespondentRepository_CreateRespondentMRA_Call struct {
	*mock.Call
}

// CreateRespondentMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - firstName string
//   - lastName string
//   - title string
//   - extID string
//   - sessKey string
//   - tz string
//   - tzAbbr string
//   - lang string
func (_e *MockQsRespondentRepository_Expecter) CreateRespondentMRA(ctx interface{}, firstName interface{}, lastName interface{}, title interface{}, extID interface{}, sessKey interface{}, tz interface{}, tzAbbr interface{}, lang interface{}) *MockQsRespondentRepository_CreateRespondentMRA_Call {
	return &MockQsRespondentRepository_CreateRespondentMRA_Call{Call: _e.mock.On("CreateRespondentMRA", ctx, firstName, lastName, title, extID, sessKey, tz, tzAbbr, lang)}
}

func (_c *MockQsRespondentRepository_CreateRespondentMRA_Call) Run(run func(ctx context.Context, firstName string, lastName string, title string, extID string, sessKey string, tz string, tzAbbr string, lang string)) *MockQsRespondentRepository_CreateRespondentMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string), args[7].(string), args[8].(string))
	})
	return _c
}

func (_c *MockQsRespondentRepository_CreateRespondentMRA_Call) Return(_a0 int64, _a1 error) *MockQsRespondentRepository_CreateRespondentMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_CreateRespondentMRA_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string, string, string) (int64, error)) *MockQsRespondentRepository_CreateRespondentMRA_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockQsRespondentRepository) GetByID(ctx context.Context, id int64) (*qs.Respondent, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *qs.Respondent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*qs.Respondent, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *qs.Respondent); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qs.Respondent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockQsRespondentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQsRespondentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockQsRespondentRepository_GetByID_Call {
	return &MockQsRespondentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockQsRespondentRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockQsRespondentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsRespondentRepository_GetByID_Call) Return(_a0 *qs.Respondent, _a1 error) *MockQsRespondentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*qs.Respondent, error)) *MockQsRespondentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommunicationAddresses provides a mock function with given fields: ctx, responderID
func (_m *MockQsRespondentRepository) GetCommunicationAddresses(ctx context.Context, responderID int64) ([]qs.RespondentCommunicationAddress, error) {
	ret := _m.Called(ctx, responderID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommunicationAddresses")
	}

	var r0 []qs.RespondentCommunicationAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]qs.RespondentCommunicationAddress, error)); ok {
		return rf(ctx, responderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []qs.RespondentCommunicationAddress); ok {
		r0 = rf(ctx, responderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.RespondentCommunicationAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, responderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_GetCommunicationAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommunicationAddresses'
type MockQsRespondentRepository_GetCommunicationAddresses_Call struct {
	*mock.Call
}

// GetCommunicationAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - responderID int64
func (_e *MockQsRespondentRepository_Expecter) GetCommunicationAddresses(ctx interface{}, responderID interface{}) *MockQsRespondentRepository_GetCommunicationAddresses_Call {
	return &MockQsRespondentRepository_GetCommunicationAddresses_Call{Call: _e.mock.On("GetCommunicationAddresses", ctx, responderID)}
}

func (_c *MockQsRespondentRepository_GetCommunicationAddresses_Call) Run(run func(ctx context.Context, responderID int64)) *MockQsRespondentRepository_GetCommunicationAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsRespondentRepository_GetCommunicationAddresses_Call) Return(_a0 []qs.RespondentCommunicationAddress, _a1 error) *MockQsRespondentRepository_GetCommunicationAddresses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_GetCommunicationAddresses_Call) RunAndReturn(run func(context.Context, int64) ([]qs.RespondentCommunicationAddress, error)) *MockQsRespondentRepository_GetCommunicationAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantIdMRA provides a mock function with given fields: ctx, timeslotID
func (_m *MockQsRespondentRepository) GetParticipantIdMRA(ctx context.Context, timeslotID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, timeslotID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantIdMRA")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, timeslotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, timeslotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, timeslotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_GetParticipantIdMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantIdMRA'
type MockQsRespondentRepository_GetParticipantIdMRA_Call struct {
	*mock.Call
}

// GetParticipantIdMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - timeslotID int64
func (_e *MockQsRespondentRepository_Expecter) GetParticipantIdMRA(ctx interface{}, timeslotID interface{}) *MockQsRespondentRepository_GetParticipantIdMRA_Call {
	return &MockQsRespondentRepository_GetParticipantIdMRA_Call{Call: _e.mock.On("GetParticipantIdMRA", ctx, timeslotID)}
}

func (_c *MockQsRespondentRepository_GetParticipantIdMRA_Call) Run(run func(ctx context.Context, timeslotID int64)) *MockQsRespondentRepository_GetParticipantIdMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsRespondentRepository_GetParticipantIdMRA_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsRespondentRepository_GetParticipantIdMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_GetParticipantIdMRA_Call) RunAndReturn(run func(context.Context, int64) ([]map[string]interface{}, error)) *MockQsRespondentRepository_GetParticipantIdMRA_Call {
	_c.Call.Return(run)
	return _c
}

// GetRescheduleTokenMRA provides a mock function with given fields: ctx, projectID, responderID
func (_m *MockQsRespondentRepository) GetRescheduleTokenMRA(ctx context.Context, projectID int64, responderID int64) (string, error) {
	ret := _m.Called(ctx, projectID, responderID)

	if len(ret) == 0 {
		panic("no return value specified for GetRescheduleTokenMRA")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (string, error)); ok {
		return rf(ctx, projectID, responderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) string); ok {
		r0 = rf(ctx, projectID, responderID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, projectID, responderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_GetRescheduleTokenMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRescheduleTokenMRA'
type MockQsRespondentRepository_GetRescheduleTokenMRA_Call struct {
	*mock.Call
}

// GetRescheduleTokenMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - responderID int64
func (_e *MockQsRespondentRepository_Expecter) GetRescheduleTokenMRA(ctx interface{}, projectID interface{}, responderID interface{}) *MockQsRespondentRepository_GetRescheduleTokenMRA_Call {
	return &MockQsRespondentRepository_GetRescheduleTokenMRA_Call{Call: _e.mock.On("GetRescheduleTokenMRA", ctx, projectID, responderID)}
}

func (_c *MockQsRespondentRepository_GetRescheduleTokenMRA_Call) Run(run func(ctx context.Context, projectID int64, responderID int64)) *MockQsRespondentRepository_GetRescheduleTokenMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockQsRespondentRepository_GetRescheduleTokenMRA_Call) Return(_a0 string, _a1 error) *MockQsRespondentRepository_GetRescheduleTokenMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_GetRescheduleTokenMRA_Call) RunAndReturn(run func(context.Context, int64, int64) (string, error)) *MockQsRespondentRepository_GetRescheduleTokenMRA_Call {
	_c.Call.Return(run)
	return _c
}

// GetRespondentByExternalIdMRA provides a mock function with given fields: ctx, externalResponderID, projectID
func (_m *MockQsRespondentRepository) GetRespondentByExternalIdMRA(ctx context.Context, externalResponderID string, projectID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, externalResponderID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetRespondentByExternalIdMRA")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, externalResponderID, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, externalResponderID, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, externalResponderID, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRespondentByExternalIdMRA'
type MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call struct {
	*mock.Call
}

// GetRespondentByExternalIdMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - externalResponderID string
//   - projectID int64
func (_e *MockQsRespondentRepository_Expecter) GetRespondentByExternalIdMRA(ctx interface{}, externalResponderID interface{}, projectID interface{}) *MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call {
	return &MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call{Call: _e.mock.On("GetRespondentByExternalIdMRA", ctx, externalResponderID, projectID)}
}

func (_c *MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call) Run(run func(ctx context.Context, externalResponderID string, projectID int64)) *MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call) RunAndReturn(run func(context.Context, string, int64) ([]map[string]interface{}, error)) *MockQsRespondentRepository_GetRespondentByExternalIdMRA_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, pageSize, search
func (_m *MockQsRespondentRepository) List(ctx context.Context, page int, pageSize int, search string) ([]qs.RespondentListRow, int, error) {
	ret := _m.Called(ctx, page, pageSize, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []qs.RespondentListRow
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) ([]qs.RespondentListRow, int, error)); ok {
		return rf(ctx, page, pageSize, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) []qs.RespondentListRow); ok {
		r0 = rf(ctx, page, pageSize, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.RespondentListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) int); ok {
		r1 = rf(ctx, page, pageSize, search)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = rf(ctx, page, pageSize, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockQsRespondentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockQsRespondentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
//   - search string
func (_e *MockQsRespondentRepository_Expecter) List(ctx interface{}, page interface{}, pageSize interface{}, search interface{}) *MockQsRespondentRepository_List_Call {
	return &MockQsRespondentRepository_List_Call{Call: _e.mock.On("List", ctx, page, pageSize, search)}
}

func (_c *MockQsRespondentRepository_List_Call) Run(run func(ctx context.Context, page int, pageSize int, search string)) *MockQsRespondentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockQsRespondentRepository_List_Call) Return(_a0 []qs.RespondentListRow, _a1 int, _a2 error) *MockQsRespondentRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockQsRespondentRepository_List_Call) RunAndReturn(run func(context.Context, int, int, string) ([]qs.RespondentListRow, int, error)) *MockQsRespondentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, fields
func (_m *MockQsRespondentRepository) Update(ctx context.Context, id int64, fields map[string]interface{}) error {
	ret := _m.Called(ctx, id, fields)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsRespondentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockQsRespondentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - fields map[string]interface{}
func (_e *MockQsRespondentRepository_Expecter) Update(ctx interface{}, id interface{}, fields interface{}) *MockQsRespondentRepository_Update_Call {
	return &MockQsRespondentRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, fields)}
}

func (_c *MockQsRespondentRepository_Update_Call) Run(run func(ctx context.Context, id int64, fields map[string]interface{})) *MockQsRespondentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockQsRespondentRepository_Update_Call) Return(_a0 error) *MockQsRespondentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsRespondentRepository_Update_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *MockQsRespondentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQsRespondentRepository creates a new instance of MockQsRespondentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQsRespondentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQsRespondentRepository {
	mock := &MockQsRespondentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
