// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	iris "github.com/InCrowd/unified-qual-api/internal/repository/iris"

	time "time"
)

// MockIrisJobsRepository is an autogenerated mock type for the JobsRepository type
type MockIrisJobsRepository struct {
	mock.Mock
}

type MockIrisJobsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIrisJobsRepository) EXPECT() *MockIrisJobsRepository_Expecter {
	return &MockIrisJobsRepository_Expecter{mock: &_m.Mock}
}

// CloseSurveyByJob provides a mock function with given fields: ctx, surveyID
func (_m *MockIrisJobsRepository) CloseSurveyByJob(ctx context.Context, surveyID int64) error {
	ret := _m.Called(ctx, surveyID)

	if len(ret) == 0 {
		panic("no return value specified for CloseSurveyByJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, surveyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisJobsRepository_CloseSurveyByJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSurveyByJob'
type MockIrisJobsRepository_CloseSurveyByJob_Call struct {
	*mock.Call
}

// CloseSurveyByJob is a helper method to define mock.On call
//   - ctx context.Context
//   - surveyID int64
func (_e *MockIrisJobsRepository_Expecter) CloseSurveyByJob(ctx interface{}, surveyID interface{}) *MockIrisJobsRepository_CloseSurveyByJob_Call {
	return &MockIrisJobsRepository_CloseSurveyByJob_Call{Call: _e.mock.On("CloseSurveyByJob", ctx, surveyID)}
}

func (_c *MockIrisJobsRepository_CloseSurveyByJob_Call) Run(run func(ctx context.Context, surveyID int64)) *MockIrisJobsRepository_CloseSurveyByJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIrisJobsRepository_CloseSurveyByJob_Call) Return(_a0 error) *MockIrisJobsRepository_CloseSurveyByJob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisJobsRepository_CloseSurveyByJob_Call) RunAndReturn(run func(context.Context, int64) error) *MockIrisJobsRepository_CloseSurveyByJob_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteProject provides a mock function with given fields: ctx, projectID
func (_m *MockIrisJobsRepository) CompleteProject(ctx context.Context, projectID int64) error {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisJobsRepository_CompleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteProject'
type MockIrisJobsRepository_CompleteProject_Call struct {
	*mock.Call
}

// CompleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockIrisJobsRepository_Expecter) CompleteProject(ctx interface{}, projectID interface{}) *MockIrisJobsRepository_CompleteProject_Call {
	return &MockIrisJobsRepository_CompleteProject_Call{Call: _e.mock.On("CompleteProject", ctx, projectID)}
}

func (_c *MockIrisJobsRepository_CompleteProject_Call) Run(run func(ctx context.Context, projectID int64)) *MockIrisJobsRepository_CompleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIrisJobsRepository_CompleteProject_Call) Return(_a0 error) *MockIrisJobsRepository_CompleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisJobsRepository_CompleteProject_Call) RunAndReturn(run func(context.Context, int64) error) *MockIrisJobsRepository_CompleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetCalendarWatchConfig provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetCalendarWatchConfig(ctx context.Context) (*iris.CalendarWatch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCalendarWatchConfig")
	}

	var r0 *iris.CalendarWatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*iris.CalendarWatch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *iris.CalendarWatch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iris.CalendarWatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetCalendarWatchConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCalendarWatchConfig'
type MockIrisJobsRepository_GetCalendarWatchConfig_Call struct {
	*mock.Call
}

// GetCalendarWatchConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetCalendarWatchConfig(ctx interface{}) *MockIrisJobsRepository_GetCalendarWatchConfig_Call {
	return &MockIrisJobsRepository_GetCalendarWatchConfig_Call{Call: _e.mock.On("GetCalendarWatchConfig", ctx)}
}

func (_c *MockIrisJobsRepository_GetCalendarWatchConfig_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetCalendarWatchConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetCalendarWatchConfig_Call) Return(_a0 *iris.CalendarWatch, _a1 error) *MockIrisJobsRepository_GetCalendarWatchConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetCalendarWatchConfig_Call) RunAndReturn(run func(context.Context) (*iris.CalendarWatch, error)) *MockIrisJobsRepository_GetCalendarWatchConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeatureFlag provides a mock function with given fields: ctx, key
func (_m *MockIrisJobsRepository) GetFeatureFlag(ctx context.Context, key string) (int64, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFeatureFlag")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetFeatureFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatureFlag'
type MockIrisJobsRepository_GetFeatureFlag_Call struct {
	*mock.Call
}

// GetFeatureFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIrisJobsRepository_Expecter) GetFeatureFlag(ctx interface{}, key interface{}) *MockIrisJobsRepository_GetFeatureFlag_Call {
	return &MockIrisJobsRepository_GetFeatureFlag_Call{Call: _e.mock.On("GetFeatureFlag", ctx, key)}
}

func (_c *MockIrisJobsRepository_GetFeatureFlag_Call) Run(run func(ctx context.Context, key string)) *MockIrisJobsRepository_GetFeatureFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetFeatureFlag_Call) Return(_a0 int64, _a1 error) *MockIrisJobsRepository_GetFeatureFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetFeatureFlag_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockIrisJobsRepository_GetFeatureFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayableTimeSlots provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetPayableTimeSlots(ctx context.Context) ([]iris.PayableTimeSlot, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPayableTimeSlots")
	}

	var r0 []iris.PayableTimeSlot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]iris.PayableTimeSlot, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []iris.PayableTimeSlot); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.PayableTimeSlot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetPayableTimeSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayableTimeSlots'
type MockIrisJobsRepository_GetPayableTimeSlots_Call struct {
	*mock.Call
}

// GetPayableTimeSlots is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetPayableTimeSlots(ctx interface{}) *MockIrisJobsRepository_GetPayableTimeSlots_Call {
	return &MockIrisJobsRepository_GetPayableTimeSlots_Call{Call: _e.mock.On("GetPayableTimeSlots", ctx)}
}

func (_c *MockIrisJobsRepository_GetPayableTimeSlots_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetPayableTimeSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetPayableTimeSlots_Call) Return(_a0 []iris.PayableTimeSlot, _a1 error) *MockIrisJobsRepository_GetPayableTimeSlots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetPayableTimeSlots_Call) RunAndReturn(run func(context.Context) ([]iris.PayableTimeSlot, error)) *MockIrisJobsRepository_GetPayableTimeSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreviousMonthTranscripts provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetPreviousMonthTranscripts(ctx context.Context) ([]iris.TranscriptRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousMonthTranscripts")
	}

	var r0 []iris.TranscriptRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]iris.TranscriptRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []iris.TranscriptRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.TranscriptRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetPreviousMonthTranscripts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreviousMonthTranscripts'
type MockIrisJobsRepository_GetPreviousMonthTranscripts_Call struct {
	*mock.Call
}

// GetPreviousMonthTranscripts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetPreviousMonthTranscripts(ctx interface{}) *MockIrisJobsRepository_GetPreviousMonthTranscripts_Call {
	return &MockIrisJobsRepository_GetPreviousMonthTranscripts_Call{Call: _e.mock.On("GetPreviousMonthTranscripts", ctx)}
}

func (_c *MockIrisJobsRepository_GetPreviousMonthTranscripts_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetPreviousMonthTranscripts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetPreviousMonthTranscripts_Call) Return(_a0 []iris.TranscriptRecord, _a1 error) *MockIrisJobsRepository_GetPreviousMonthTranscripts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetPreviousMonthTranscripts_Call) RunAndReturn(run func(context.Context) ([]iris.TranscriptRecord, error)) *MockIrisJobsRepository_GetPreviousMonthTranscripts_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectsToComplete provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetProjectsToComplete(ctx context.Context) ([]iris.ProjectToComplete, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectsToComplete")
	}

	var r0 []iris.ProjectToComplete
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]iris.ProjectToComplete, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []iris.ProjectToComplete); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.ProjectToComplete)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetProjectsToComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectsToComplete'
type MockIrisJobsRepository_GetProjectsToComplete_Call struct {
	*mock.Call
}

// GetProjectsToComplete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetProjectsToComplete(ctx interface{}) *MockIrisJobsRepository_GetProjectsToComplete_Call {
	return &MockIrisJobsRepository_GetProjectsToComplete_Call{Call: _e.mock.On("GetProjectsToComplete", ctx)}
}

func (_c *MockIrisJobsRepository_GetProjectsToComplete_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetProjectsToComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetProjectsToComplete_Call) Return(_a0 []iris.ProjectToComplete, _a1 error) *MockIrisJobsRepository_GetProjectsToComplete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetProjectsToComplete_Call) RunAndReturn(run func(context.Context) ([]iris.ProjectToComplete, error)) *MockIrisJobsRepository_GetProjectsToComplete_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaleConferenceHashes provides a mock function with given fields: ctx, hashes
func (_m *MockIrisJobsRepository) GetStaleConferenceHashes(ctx context.Context, hashes []string) ([]string, error) {
	ret := _m.Called(ctx, hashes)

	if len(ret) == 0 {
		panic("no return value specified for GetStaleConferenceHashes")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return rf(ctx, hashes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(ctx, hashes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, hashes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetStaleConferenceHashes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaleConferenceHashes'
type MockIrisJobsRepository_GetStaleConferenceHashes_Call struct {
	*mock.Call
}

// GetStaleConferenceHashes is a helper method to define mock.On call
//   - ctx context.Context
//   - hashes []string
func (_e *MockIrisJobsRepository_Expecter) GetStaleConferenceHashes(ctx interface{}, hashes interface{}) *MockIrisJobsRepository_GetStaleConferenceHashes_Call {
	return &MockIrisJobsRepository_GetStaleConferenceHashes_Call{Call: _e.mock.On("GetStaleConferenceHashes", ctx, hashes)}
}

func (_c *MockIrisJobsRepository_GetStaleConferenceHashes_Call) Run(run func(ctx context.Context, hashes []string)) *MockIrisJobsRepository_GetStaleConferenceHashes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetStaleConferenceHashes_Call) Return(_a0 []string, _a1 error) *MockIrisJobsRepository_GetStaleConferenceHashes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetStaleConferenceHashes_Call) RunAndReturn(run func(context.Context, []string) ([]string, error)) *MockIrisJobsRepository_GetStaleConferenceHashes_Call {
	_c.Call.Return(run)
	return _c
}

// GetSurveyCrowdTypes provides a mock function with given fields: ctx, surveyID
func (_m *MockIrisJobsRepository) GetSurveyCrowdTypes(ctx context.Context, surveyID int64) ([]int64, error) {
	ret := _m.Called(ctx, surveyID)

	if len(ret) == 0 {
		panic("no return value specified for GetSurveyCrowdTypes")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, surveyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, surveyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, surveyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetSurveyCrowdTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSurveyCrowdTypes'
type MockIrisJobsRepository_GetSurveyCrowdTypes_Call struct {
	*mock.Call
}

// GetSurveyCrowdTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - surveyID int64
func (_e *MockIrisJobsRepository_Expecter) GetSurveyCrowdTypes(ctx interface{}, surveyID interface{}) *MockIrisJobsRepository_GetSurveyCrowdTypes_Call {
	return &MockIrisJobsRepository_GetSurveyCrowdTypes_Call{Call: _e.mock.On("GetSurveyCrowdTypes", ctx, surveyID)}
}

func (_c *MockIrisJobsRepository_GetSurveyCrowdTypes_Call) Run(run func(ctx context.Context, surveyID int64)) *MockIrisJobsRepository_GetSurveyCrowdTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetSurveyCrowdTypes_Call) Return(_a0 []int64, _a1 error) *MockIrisJobsRepository_GetSurveyCrowdTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetSurveyCrowdTypes_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *MockIrisJobsRepository_GetSurveyCrowdTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetSurveysToClose provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetSurveysToClose(ctx context.Context) ([]iris.SurveyToClose, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSurveysToClose")
	}

	var r0 []iris.SurveyToClose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]iris.SurveyToClose, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []iris.SurveyToClose); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.SurveyToClose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetSurveysToClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSurveysToClose'
type MockIrisJobsRepository_GetSurveysToClose_Call struct {
	*mock.Call
}

// GetSurveysToClose is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetSurveysToClose(ctx interface{}) *MockIrisJobsRepository_GetSurveysToClose_Call {
	return &MockIrisJobsRepository_GetSurveysToClose_Call{Call: _e.mock.On("GetSurveysToClose", ctx)}
}

func (_c *MockIrisJobsRepository_GetSurveysToClose_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetSurveysToClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetSurveysToClose_Call) Return(_a0 []iris.SurveyToClose, _a1 error) *MockIrisJobsRepository_GetSurveysToClose_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetSurveysToClose_Call) RunAndReturn(run func(context.Context) ([]iris.SurveyToClose, error)) *MockIrisJobsRepository_GetSurveysToClose_Call {
	_c.Call.Return(run)
	return _c
}

// GetTomorrowInterviews provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetTomorrowInterviews(ctx context.Context) ([]iris.InterviewReminder, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTomorrowInterviews")
	}

	var r0 []iris.InterviewReminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]iris.InterviewReminder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []iris.InterviewReminder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.InterviewReminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetTomorrowInterviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTomorrowInterviews'
type MockIrisJobsRepository_GetTomorrowInterviews_Call struct {
	*mock.Call
}

// GetTomorrowInterviews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetTomorrowInterviews(ctx interface{}) *MockIrisJobsRepository_GetTomorrowInterviews_Call {
	return &MockIrisJobsRepository_GetTomorrowInterviews_Call{Call: _e.mock.On("GetTomorrowInterviews", ctx)}
}

func (_c *MockIrisJobsRepository_GetTomorrowInterviews_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetTomorrowInterviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetTomorrowInterviews_Call) Return(_a0 []iris.InterviewReminder, _a1 error) *MockIrisJobsRepository_GetTomorrowInterviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetTomorrowInterviews_Call) RunAndReturn(run func(context.Context) ([]iris.InterviewReminder, error)) *MockIrisJobsRepository_GetTomorrowInterviews_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnconfirmedAnswers provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetUnconfirmedAnswers(ctx context.Context) ([]iris.UnconfirmedAnswer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnconfirmedAnswers")
	}

	var r0 []iris.UnconfirmedAnswer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]iris.UnconfirmedAnswer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []iris.UnconfirmedAnswer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.UnconfirmedAnswer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetUnconfirmedAnswers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnconfirmedAnswers'
type MockIrisJobsRepository_GetUnconfirmedAnswers_Call struct {
	*mock.Call
}

// GetUnconfirmedAnswers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetUnconfirmedAnswers(ctx interface{}) *MockIrisJobsRepository_GetUnconfirmedAnswers_Call {
	return &MockIrisJobsRepository_GetUnconfirmedAnswers_Call{Call: _e.mock.On("GetUnconfirmedAnswers", ctx)}
}

func (_c *MockIrisJobsRepository_GetUnconfirmedAnswers_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetUnconfirmedAnswers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetUnconfirmedAnswers_Call) Return(_a0 []iris.UnconfirmedAnswer, _a1 error) *MockIrisJobsRepository_GetUnconfirmedAnswers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetUnconfirmedAnswers_Call) RunAndReturn(run func(context.Context) ([]iris.UnconfirmedAnswer, error)) *MockIrisJobsRepository_GetUnconfirmedAnswers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpcomingInterviews provides a mock function with given fields: ctx
func (_m *MockIrisJobsRepository) GetUpcomingInterviews(ctx context.Context) ([]iris.InterviewReminder, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUpcomingInterviews")
	}

	var r0 []iris.InterviewReminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]iris.InterviewReminder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []iris.InterviewReminder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.InterviewReminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GetUpcomingInterviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpcomingInterviews'
type MockIrisJobsRepository_GetUpcomingInterviews_Call struct {
	*mock.Call
}

// GetUpcomingInterviews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIrisJobsRepository_Expecter) GetUpcomingInterviews(ctx interface{}) *MockIrisJobsRepository_GetUpcomingInterviews_Call {
	return &MockIrisJobsRepository_GetUpcomingInterviews_Call{Call: _e.mock.On("GetUpcomingInterviews", ctx)}
}

func (_c *MockIrisJobsRepository_GetUpcomingInterviews_Call) Run(run func(ctx context.Context)) *MockIrisJobsRepository_GetUpcomingInterviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GetUpcomingInterviews_Call) Return(_a0 []iris.InterviewReminder, _a1 error) *MockIrisJobsRepository_GetUpcomingInterviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GetUpcomingInterviews_Call) RunAndReturn(run func(context.Context) ([]iris.InterviewReminder, error)) *MockIrisJobsRepository_GetUpcomingInterviews_Call {
	_c.Call.Return(run)
	return _c
}

// GrantCredit provides a mock function with given fields: ctx, params
func (_m *MockIrisJobsRepository) GrantCredit(ctx context.Context, params iris.CreditParams) (int64, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GrantCredit")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, iris.CreditParams) (int64, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, iris.CreditParams) int64); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, iris.CreditParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisJobsRepository_GrantCredit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantCredit'
type MockIrisJobsRepository_GrantCredit_Call struct {
	*mock.Call
}

// GrantCredit is a helper method to define mock.On call
//   - ctx context.Context
//   - params iris.CreditParams
func (_e *MockIrisJobsRepository_Expecter) GrantCredit(ctx interface{}, params interface{}) *MockIrisJobsRepository_GrantCredit_Call {
	return &MockIrisJobsRepository_GrantCredit_Call{Call: _e.mock.On("GrantCredit", ctx, params)}
}

func (_c *MockIrisJobsRepository_GrantCredit_Call) Run(run func(ctx context.Context, params iris.CreditParams)) *MockIrisJobsRepository_GrantCredit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iris.CreditParams))
	})
	return _c
}

func (_c *MockIrisJobsRepository_GrantCredit_Call) Return(_a0 int64, _a1 error) *MockIrisJobsRepository_GrantCredit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisJobsRepository_GrantCredit_Call) RunAndReturn(run func(context.Context, iris.CreditParams) (int64, error)) *MockIrisJobsRepository_GrantCredit_Call {
	_c.Call.Return(run)
	return _c
}

// LogActivity provides a mock function with given fields: ctx, params
func (_m *MockIrisJobsRepository) LogActivity(ctx context.Context, params iris.ActivityLogParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for LogActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, iris.ActivityLogParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisJobsRepository_LogActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogActivity'
type MockIrisJobsRepository_LogActivity_Call struct {
	*mock.Call
}

// LogActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - params iris.ActivityLogParams
func (_e *MockIrisJobsRepository_Expecter) LogActivity(ctx interface{}, params interface{}) *MockIrisJobsRepository_LogActivity_Call {
	return &MockIrisJobsRepository_LogActivity_Call{Call: _e.mock.On("LogActivity", ctx, params)}
}

func (_c *MockIrisJobsRepository_LogActivity_Call) Run(run func(ctx context.Context, params iris.ActivityLogParams)) *MockIrisJobsRepository_LogActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(iris.ActivityLogParams))
	})
	return _c
}

func (_c *MockIrisJobsRepository_LogActivity_Call) Return(_a0 error) *MockIrisJobsRepository_LogActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisJobsRepository_LogActivity_Call) RunAndReturn(run func(context.Context, iris.ActivityLogParams) error) *MockIrisJobsRepository_LogActivity_Call {
	_c.Call.Return(run)
	return _c
}

// MarkHonorariumPaid provides a mock function with given fields: ctx, timeSlotID, creditID
func (_m *MockIrisJobsRepository) MarkHonorariumPaid(ctx context.Context, timeSlotID int64, creditID int64) error {
	ret := _m.Called(ctx, timeSlotID, creditID)

	if len(ret) == 0 {
		panic("no return value specified for MarkHonorariumPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, timeSlotID, creditID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisJobsRepository_MarkHonorariumPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkHonorariumPaid'
type MockIrisJobsRepository_MarkHonorariumPaid_Call struct {
	*mock.Call
}

// MarkHonorariumPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
//   - creditID int64
func (_e *MockIrisJobsRepository_Expecter) MarkHonorariumPaid(ctx interface{}, timeSlotID interface{}, creditID interface{}) *MockIrisJobsRepository_MarkHonorariumPaid_Call {
	return &MockIrisJobsRepository_MarkHonorariumPaid_Call{Call: _e.mock.On("MarkHonorariumPaid", ctx, timeSlotID, creditID)}
}

func (_c *MockIrisJobsRepository_MarkHonorariumPaid_Call) Run(run func(ctx context.Context, timeSlotID int64, creditID int64)) *MockIrisJobsRepository_MarkHonorariumPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIrisJobsRepository_MarkHonorariumPaid_Call) Return(_a0 error) *MockIrisJobsRepository_MarkHonorariumPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisJobsRepository_MarkHonorariumPaid_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockIrisJobsRepository_MarkHonorariumPaid_Call {
	_c.Call.Return(run)
	return _c
}

// SetSurveyToInReview provides a mock function with given fields: ctx, surveyID
func (_m *MockIrisJobsRepository) SetSurveyToInReview(ctx context.Context, surveyID int64) error {
	ret := _m.Called(ctx, surveyID)

	if len(ret) == 0 {
		panic("no return value specified for SetSurveyToInReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, surveyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisJobsRepository_SetSurveyToInReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSurveyToInReview'
type MockIrisJobsRepository_SetSurveyToInReview_Call struct {
	*mock.Call
}

// SetSurveyToInReview is a helper method to define mock.On call
//   - ctx context.Context
//   - surveyID int64
func (_e *MockIrisJobsRepository_Expecter) SetSurveyToInReview(ctx interface{}, surveyID interface{}) *MockIrisJobsRepository_SetSurveyToInReview_Call {
	return &MockIrisJobsRepository_SetSurveyToInReview_Call{Call: _e.mock.On("SetSurveyToInReview", ctx, surveyID)}
}

func (_c *MockIrisJobsRepository_SetSurveyToInReview_Call) Run(run func(ctx context.Context, surveyID int64)) *MockIrisJobsRepository_SetSurveyToInReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIrisJobsRepository_SetSurveyToInReview_Call) Return(_a0 error) *MockIrisJobsRepository_SetSurveyToInReview_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisJobsRepository_SetSurveyToInReview_Call) RunAndReturn(run func(context.Context, int64) error) *MockIrisJobsRepository_SetSurveyToInReview_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCalendarWatch provides a mock function with given fields: ctx, watchID, resourceID, expiration
func (_m *MockIrisJobsRepository) UpdateCalendarWatch(ctx context.Context, watchID string, resourceID string, expiration time.Time) error {
	ret := _m.Called(ctx, watchID, resourceID, expiration)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCalendarWatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, watchID, resourceID, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisJobsRepository_UpdateCalendarWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCalendarWatch'
type MockIrisJobsRepository_UpdateCalendarWatch_Call struct {
	*mock.Call
}

// UpdateCalendarWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - watchID string
//   - resourceID string
//   - expiration time.Time
func (_e *MockIrisJobsRepository_Expecter) UpdateCalendarWatch(ctx interface{}, watchID interface{}, resourceID interface{}, expiration interface{}) *MockIrisJobsRepository_UpdateCalendarWatch_Call {
	return &MockIrisJobsRepository_UpdateCalendarWatch_Call{Call: _e.mock.On("UpdateCalendarWatch", ctx, watchID, resourceID, expiration)}
}

func (_c *MockIrisJobsRepository_UpdateCalendarWatch_Call) Run(run func(ctx context.Context, watchID string, resourceID string, expiration time.Time)) *MockIrisJobsRepository_UpdateCalendarWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockIrisJobsRepository_UpdateCalendarWatch_Call) Return(_a0 error) *MockIrisJobsRepository_UpdateCalendarWatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisJobsRepository_UpdateCalendarWatch_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *MockIrisJobsRepository_UpdateCalendarWatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTranscriptTotal provides a mock function with given fields: ctx, id, total
func (_m *MockIrisJobsRepository) UpdateTranscriptTotal(ctx context.Context, id int64, total float64) error {
	ret := _m.Called(ctx, id, total)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTranscriptTotal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64) error); ok {
		r0 = rf(ctx, id, total)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisJobsRepository_UpdateTranscriptTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTranscriptTotal'
type MockIrisJobsRepository_UpdateTranscriptTotal_Call struct {
	*mock.Call
}

// UpdateTranscriptTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - total float64
func (_e *MockIrisJobsRepository_Expecter) UpdateTranscriptTotal(ctx interface{}, id interface{}, total interface{}) *MockIrisJobsRepository_UpdateTranscriptTotal_Call {
	return &MockIrisJobsRepository_UpdateTranscriptTotal_Call{Call: _e.mock.On("UpdateTranscriptTotal", ctx, id, total)}
}

func (_c *MockIrisJobsRepository_UpdateTranscriptTotal_Call) Run(run func(ctx context.Context, id int64, total float64)) *MockIrisJobsRepository_UpdateTranscriptTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(float64))
	})
	return _c
}

func (_c *MockIrisJobsRepository_UpdateTranscriptTotal_Call) Return(_a0 error) *MockIrisJobsRepository_UpdateTranscriptTotal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisJobsRepository_UpdateTranscriptTotal_Call) RunAndReturn(run func(context.Context, int64, float64) error) *MockIrisJobsRepository_UpdateTranscriptTotal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIrisJobsRepository creates a new instance of MockIrisJobsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIrisJobsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIrisJobsRepository {
	mock := &MockIrisJobsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
