// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	qs "github.com/InCrowd/unified-qual-api/internal/repository/qs"
)

// MockQsSurveyRepository is an autogenerated mock type for the SurveyRepository type
type MockQsSurveyRepository struct {
	mock.Mock
}

type MockQsSurveyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQsSurveyRepository) EXPECT() *MockQsSurveyRepository_Expecter {
	return &MockQsSurveyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, title, status, questions, rules
func (_m *MockQsSurveyRepository) Create(ctx context.Context, projectID *int64, title string, status string, questions json.RawMessage, rules json.RawMessage) (int64, error) {
	ret := _m.Called(ctx, projectID, title, status, questions, rules)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int64, string, string, json.RawMessage, json.RawMessage) (int64, error)); ok {
		return rf(ctx, projectID, title, status, questions, rules)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int64, string, string, json.RawMessage, json.RawMessage) int64); ok {
		r0 = rf(ctx, projectID, title, status, questions, rules)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int64, string, string, json.RawMessage, json.RawMessage) error); ok {
		r1 = rf(ctx, projectID, title, status, questions, rules)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsSurveyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockQsSurveyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID *int64
//   - title string
//   - status string
//   - questions json.RawMessage
//   - rules json.RawMessage
func (_e *MockQsSurveyRepository_Expecter) Create(ctx interface{}, projectID interface{}, title interface{}, status interface{}, questions interface{}, rules interface{}) *MockQsSurveyRepository_Create_Call {
	return &MockQsSurveyRepository_Create_Call{Call: _e.mock.On("Create", ctx, projectID, title, status, questions, rules)}
}

func (_c *MockQsSurveyRepository_Create_Call) Run(run func(ctx context.Context, projectID *int64, title string, status string, questions json.RawMessage, rules json.RawMessage)) *MockQsSurveyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int64), args[2].(string), args[3].(string), args[4].(json.RawMessage), args[5].(json.RawMessage))
	})
	return _c
}

func (_c *MockQsSurveyRepository_Create_Call) Return(_a0 int64, _a1 error) *MockQsSurveyRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsSurveyRepository_Create_Call) RunAndReturn(run func(context.Context, *int64, string, string, json.RawMessage, json.RawMessage) (int64, error)) *MockQsSurveyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockQsSurveyRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsSurveyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockQsSurveyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQsSurveyRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockQsSurveyRepository_Delete_Call {
	return &MockQsSurveyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockQsSurveyRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockQsSurveyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsSurveyRepository_Delete_Call) Return(_a0 error) *MockQsSurveyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsSurveyRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockQsSurveyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureTable provides a mock function with given fields: ctx
func (_m *MockQsSurveyRepository) EnsureTable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsSurveyRepository_EnsureTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureTable'
type MockQsSurveyRepository_EnsureTable_Call struct {
	*mock.Call
}

// EnsureTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsSurveyRepository_Expecter) EnsureTable(ctx interface{}) *MockQsSurveyRepository_EnsureTable_Call {
	return &MockQsSurveyRepository_EnsureTable_Call{Call: _e.mock.On("EnsureTable", ctx)}
}

func (_c *MockQsSurveyRepository_EnsureTable_Call) Run(run func(ctx context.Context)) *MockQsSurveyRepository_EnsureTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsSurveyRepository_EnsureTable_Call) Return(_a0 error) *MockQsSurveyRepository_EnsureTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsSurveyRepository_EnsureTable_Call) RunAndReturn(run func(context.Context) error) *MockQsSurveyRepository_EnsureTable_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockQsSurveyRepository) GetByID(ctx context.Context, id int64) (*qs.SurveyRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *qs.SurveyRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*qs.SurveyRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *qs.SurveyRow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qs.SurveyRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsSurveyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockQsSurveyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQsSurveyRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockQsSurveyRepository_GetByID_Call {
	return &MockQsSurveyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockQsSurveyRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockQsSurveyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsSurveyRepository_GetByID_Call) Return(_a0 *qs.SurveyRow, _a1 error) *MockQsSurveyRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsSurveyRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*qs.SurveyRow, error)) *MockQsSurveyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSurveyByIdMRA provides a mock function with given fields: ctx, surveyID
func (_m *MockQsSurveyRepository) GetSurveyByIdMRA(ctx context.Context, surveyID int64) (map[string]interface{}, error) {
	ret := _m.Called(ctx, surveyID)

	if len(ret) == 0 {
		panic("no return value specified for GetSurveyByIdMRA")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[string]interface{}, error)); ok {
		return rf(ctx, surveyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[string]interface{}); ok {
		r0 = rf(ctx, surveyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, surveyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsSurveyRepository_GetSurveyByIdMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSurveyByIdMRA'
type MockQsSurveyRepository_GetSurveyByIdMRA_Call struct {
	*mock.Call
}

// GetSurveyByIdMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - surveyID int64
func (_e *MockQsSurveyRepository_Expecter) GetSurveyByIdMRA(ctx interface{}, surveyID interface{}) *MockQsSurveyRepository_GetSurveyByIdMRA_Call {
	return &MockQsSurveyRepository_GetSurveyByIdMRA_Call{Call: _e.mock.On("GetSurveyByIdMRA", ctx, surveyID)}
}

func (_c *MockQsSurveyRepository_GetSurveyByIdMRA_Call) Run(run func(ctx context.Context, surveyID int64)) *MockQsSurveyRepository_GetSurveyByIdMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsSurveyRepository_GetSurveyByIdMRA_Call) Return(_a0 map[string]interface{}, _a1 error) *MockQsSurveyRepository_GetSurveyByIdMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsSurveyRepository_GetSurveyByIdMRA_Call) RunAndReturn(run func(context.Context, int64) (map[string]interface{}, error)) *MockQsSurveyRepository_GetSurveyByIdMRA_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, search
func (_m *MockQsSurveyRepository) List(ctx context.Context, search string) ([]qs.SurveyRow, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []qs.SurveyRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]qs.SurveyRow, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []qs.SurveyRow); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.SurveyRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsSurveyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockQsSurveyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
func (_e *MockQsSurveyRepository_Expecter) List(ctx interface{}, search interface{}) *MockQsSurveyRepository_List_Call {
	return &MockQsSurveyRepository_List_Call{Call: _e.mock.On("List", ctx, search)}
}

func (_c *MockQsSurveyRepository_List_Call) Run(run func(ctx context.Context, search string)) *MockQsSurveyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQsSurveyRepository_List_Call) Return(_a0 []qs.SurveyRow, _a1 error) *MockQsSurveyRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsSurveyRepository_List_Call) RunAndReturn(run func(context.Context, string) ([]qs.SurveyRow, error)) *MockQsSurveyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, title, status, questions, rules
func (_m *MockQsSurveyRepository) Update(ctx context.Context, id int64, title string, status string, questions json.RawMessage, rules json.RawMessage) error {
	ret := _m.Called(ctx, id, title, status, questions, rules)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, json.RawMessage, json.RawMessage) error); ok {
		r0 = rf(ctx, id, title, status, questions, rules)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsSurveyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockQsSurveyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - title string
//   - status string
//   - questions json.RawMessage
//   - rules json.RawMessage
func (_e *MockQsSurveyRepository_Expecter) Update(ctx interface{}, id interface{}, title interface{}, status interface{}, questions interface{}, rules interface{}) *MockQsSurveyRepository_Update_Call {
	return &MockQsSurveyRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, title, status, questions, rules)}
}

func (_c *MockQsSurveyRepository_Update_Call) Run(run func(ctx context.Context, id int64, title string, status string, questions json.RawMessage, rules json.RawMessage)) *MockQsSurveyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string), args[4].(json.RawMessage), args[5].(json.RawMessage))
	})
	return _c
}

func (_c *MockQsSurveyRepository_Update_Call) Return(_a0 error) *MockQsSurveyRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsSurveyRepository_Update_Call) RunAndReturn(run func(context.Context, int64, string, string, json.RawMessage, json.RawMessage) error) *MockQsSurveyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQsSurveyRepository creates a new instance of MockQsSurveyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQsSurveyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQsSurveyRepository {
	mock := &MockQsSurveyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
