// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	qs "github.com/InCrowd/unified-qual-api/internal/repository/qs"
)

// MockQsAnswerRepository is an autogenerated mock type for the AnswerRepository type
type MockQsAnswerRepository struct {
	mock.Mock
}

type MockQsAnswerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQsAnswerRepository) EXPECT() *MockQsAnswerRepository_Expecter {
	return &MockQsAnswerRepository_Expecter{mock: &_m.Mock}
}

// CreateCustomHonorarium provides a mock function with given fields: ctx, timeSlotID, amount, reason
func (_m *MockQsAnswerRepository) CreateCustomHonorarium(ctx context.Context, timeSlotID int64, amount int, reason string) (int64, error) {
	ret := _m.Called(ctx, timeSlotID, amount, reason)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomHonorarium")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string) (int64, error)); ok {
		return rf(ctx, timeSlotID, amount, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string) int64); ok {
		r0 = rf(ctx, timeSlotID, amount, reason)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, string) error); ok {
		r1 = rf(ctx, timeSlotID, amount, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_CreateCustomHonorarium_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomHonorarium'
type MockQsAnswerRepository_CreateCustomHonorarium_Call struct {
	*mock.Call
}

// CreateCustomHonorarium is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
//   - amount int
//   - reason string
func (_e *MockQsAnswerRepository_Expecter) CreateCustomHonorarium(ctx interface{}, timeSlotID interface{}, amount interface{}, reason interface{}) *MockQsAnswerRepository_CreateCustomHonorarium_Call {
	return &MockQsAnswerRepository_CreateCustomHonorarium_Call{Call: _e.mock.On("CreateCustomHonorarium", ctx, timeSlotID, amount, reason)}
}

func (_c *MockQsAnswerRepository_CreateCustomHonorarium_Call) Run(run func(ctx context.Context, timeSlotID int64, amount int, reason string)) *MockQsAnswerRepository_CreateCustomHonorarium_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockQsAnswerRepository_CreateCustomHonorarium_Call) Return(_a0 int64, _a1 error) *MockQsAnswerRepository_CreateCustomHonorarium_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_CreateCustomHonorarium_Call) RunAndReturn(run func(context.Context, int64, int, string) (int64, error)) *MockQsAnswerRepository_CreateCustomHonorarium_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExternalPayment provides a mock function with given fields: ctx, timeSlotID, amount, paymentType, status, externalRef
func (_m *MockQsAnswerRepository) CreateExternalPayment(ctx context.Context, timeSlotID int64, amount int, paymentType string, status string, externalRef string) (int64, error) {
	ret := _m.Called(ctx, timeSlotID, amount, paymentType, status, externalRef)

	if len(ret) == 0 {
		panic("no return value specified for CreateExternalPayment")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string, string, string) (int64, error)); ok {
		return rf(ctx, timeSlotID, amount, paymentType, status, externalRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string, string, string) int64); ok {
		r0 = rf(ctx, timeSlotID, amount, paymentType, status, externalRef)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, string, string, string) error); ok {
		r1 = rf(ctx, timeSlotID, amount, paymentType, status, externalRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_CreateExternalPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExternalPayment'
type MockQsAnswerRepository_CreateExternalPayment_Call struct {
	*mock.Call
}

// CreateExternalPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
//   - amount int
//   - paymentType string
//   - status string
//   - externalRef string
func (_e *MockQsAnswerRepository_Expecter) CreateExternalPayment(ctx interface{}, timeSlotID interface{}, amount interface{}, paymentType interface{}, status interface{}, externalRef interface{}) *MockQsAnswerRepository_CreateExternalPayment_Call {
	return &MockQsAnswerRepository_CreateExternalPayment_Call{Call: _e.mock.On("CreateExternalPayment", ctx, timeSlotID, amount, paymentType, status, externalRef)}
}

func (_c *MockQsAnswerRepository_CreateExternalPayment_Call) Run(run func(ctx context.Context, timeSlotID int64, amount int, paymentType string, status string, externalRef string)) *MockQsAnswerRepository_CreateExternalPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockQsAnswerRepository_CreateExternalPayment_Call) Return(_a0 int64, _a1 error) *MockQsAnswerRepository_CreateExternalPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_CreateExternalPayment_Call) RunAndReturn(run func(context.Context, int64, int, string, string, string) (int64, error)) *MockQsAnswerRepository_CreateExternalPayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentRecord provides a mock function with given fields: ctx, timeSlotID, amount, paymentType, status
func (_m *MockQsAnswerRepository) CreatePaymentRecord(ctx context.Context, timeSlotID int64, amount int, paymentType string, status string) (int64, error) {
	ret := _m.Called(ctx, timeSlotID, amount, paymentType, status)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentRecord")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string, string) (int64, error)); ok {
		return rf(ctx, timeSlotID, amount, paymentType, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, string, string) int64); ok {
		r0 = rf(ctx, timeSlotID, amount, paymentType, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, string, string) error); ok {
		r1 = rf(ctx, timeSlotID, amount, paymentType, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_CreatePaymentRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentRecord'
type MockQsAnswerRepository_CreatePaymentRecord_Call struct {
	*mock.Call
}

// CreatePaymentRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
//   - amount int
//   - paymentType string
//   - status string
func (_e *MockQsAnswerRepository_Expecter) CreatePaymentRecord(ctx interface{}, timeSlotID interface{}, amount interface{}, paymentType interface{}, status interface{}) *MockQsAnswerRepository_CreatePaymentRecord_Call {
	return &MockQsAnswerRepository_CreatePaymentRecord_Call{Call: _e.mock.On("CreatePaymentRecord", ctx, timeSlotID, amount, paymentType, status)}
}

func (_c *MockQsAnswerRepository_CreatePaymentRecord_Call) Run(run func(ctx context.Context, timeSlotID int64, amount int, paymentType string, status string)) *MockQsAnswerRepository_CreatePaymentRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockQsAnswerRepository_CreatePaymentRecord_Call) Return(_a0 int64, _a1 error) *MockQsAnswerRepository_CreatePaymentRecord_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_CreatePaymentRecord_Call) RunAndReturn(run func(context.Context, int64, int, string, string) (int64, error)) *MockQsAnswerRepository_CreatePaymentRecord_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTopicTranslation provides a mock function with given fields: ctx, topicID, languageCode
func (_m *MockQsAnswerRepository) DeleteTopicTranslation(ctx context.Context, topicID int64, languageCode string) error {
	ret := _m.Called(ctx, topicID, languageCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTopicTranslation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, topicID, languageCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsAnswerRepository_DeleteTopicTranslation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTopicTranslation'
type MockQsAnswerRepository_DeleteTopicTranslation_Call struct {
	*mock.Call
}

// DeleteTopicTranslation is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int64
//   - languageCode string
func (_e *MockQsAnswerRepository_Expecter) DeleteTopicTranslation(ctx interface{}, topicID interface{}, languageCode interface{}) *MockQsAnswerRepository_DeleteTopicTranslation_Call {
	return &MockQsAnswerRepository_DeleteTopicTranslation_Call{Call: _e.mock.On("DeleteTopicTranslation", ctx, topicID, languageCode)}
}

func (_c *MockQsAnswerRepository_DeleteTopicTranslation_Call) Run(run func(ctx context.Context, topicID int64, languageCode string)) *MockQsAnswerRepository_DeleteTopicTranslation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockQsAnswerRepository_DeleteTopicTranslation_Call) Return(_a0 error) *MockQsAnswerRepository_DeleteTopicTranslation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsAnswerRepository_DeleteTopicTranslation_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockQsAnswerRepository_DeleteTopicTranslation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTranslation provides a mock function with given fields: ctx, projectID, languageCode
func (_m *MockQsAnswerRepository) DeleteTranslation(ctx context.Context, projectID int64, languageCode string) error {
	ret := _m.Called(ctx, projectID, languageCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTranslation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, projectID, languageCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsAnswerRepository_DeleteTranslation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTranslation'
type MockQsAnswerRepository_DeleteTranslation_Call struct {
	*mock.Call
}

// DeleteTranslation is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - languageCode string
func (_e *MockQsAnswerRepository_Expecter) DeleteTranslation(ctx interface{}, projectID interface{}, languageCode interface{}) *MockQsAnswerRepository_DeleteTranslation_Call {
	return &MockQsAnswerRepository_DeleteTranslation_Call{Call: _e.mock.On("DeleteTranslation", ctx, projectID, languageCode)}
}

func (_c *MockQsAnswerRepository_DeleteTranslation_Call) Run(run func(ctx context.Context, projectID int64, languageCode string)) *MockQsAnswerRepository_DeleteTranslation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockQsAnswerRepository_DeleteTranslation_Call) Return(_a0 error) *MockQsAnswerRepository_DeleteTranslation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsAnswerRepository_DeleteTranslation_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockQsAnswerRepository_DeleteTranslation_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommunicationTemplate provides a mock function with given fields: ctx, name
func (_m *MockQsAnswerRepository) GetCommunicationTemplate(ctx context.Context, name string) (*qs.CommunicationTemplate, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCommunicationTemplate")
	}

	var r0 *qs.CommunicationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*qs.CommunicationTemplate, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *qs.CommunicationTemplate); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qs.CommunicationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_GetCommunicationTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommunicationTemplate'
type MockQsAnswerRepository_GetCommunicationTemplate_Call struct {
	*mock.Call
}

// GetCommunicationTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQsAnswerRepository_Expecter) GetCommunicationTemplate(ctx interface{}, name interface{}) *MockQsAnswerRepository_GetCommunicationTemplate_Call {
	return &MockQsAnswerRepository_GetCommunicationTemplate_Call{Call: _e.mock.On("GetCommunicationTemplate", ctx, name)}
}

func (_c *MockQsAnswerRepository_GetCommunicationTemplate_Call) Run(run func(ctx context.Context, name string)) *MockQsAnswerRepository_GetCommunicationTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQsAnswerRepository_GetCommunicationTemplate_Call) Return(_a0 *qs.CommunicationTemplate, _a1 error) *MockQsAnswerRepository_GetCommunicationTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_GetCommunicationTemplate_Call) RunAndReturn(run func(context.Context, string) (*qs.CommunicationTemplate, error)) *MockQsAnswerRepository_GetCommunicationTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetails provides a mock function with given fields: ctx, answerID
func (_m *MockQsAnswerRepository) GetDetails(ctx context.Context, answerID int64) ([]qs.AnswerDetail, error) {
	ret := _m.Called(ctx, answerID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetails")
	}

	var r0 []qs.AnswerDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]qs.AnswerDetail, error)); ok {
		return rf(ctx, answerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []qs.AnswerDetail); ok {
		r0 = rf(ctx, answerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.AnswerDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, answerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_GetDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetails'
type MockQsAnswerRepository_GetDetails_Call struct {
	*mock.Call
}

// GetDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - answerID int64
func (_e *MockQsAnswerRepository_Expecter) GetDetails(ctx interface{}, answerID interface{}) *MockQsAnswerRepository_GetDetails_Call {
	return &MockQsAnswerRepository_GetDetails_Call{Call: _e.mock.On("GetDetails", ctx, answerID)}
}

func (_c *MockQsAnswerRepository_GetDetails_Call) Run(run func(ctx context.Context, answerID int64)) *MockQsAnswerRepository_GetDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsAnswerRepository_GetDetails_Call) Return(_a0 []qs.AnswerDetail, _a1 error) *MockQsAnswerRepository_GetDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_GetDetails_Call) RunAndReturn(run func(context.Context, int64) ([]qs.AnswerDetail, error)) *MockQsAnswerRepository_GetDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantEligibility provides a mock function with given fields: ctx, responderID, projectID
func (_m *MockQsAnswerRepository) GetParticipantEligibility(ctx context.Context, responderID int64, projectID int64) (map[string]interface{}, error) {
	ret := _m.Called(ctx, responderID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantEligibility")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (map[string]interface{}, error)); ok {
		return rf(ctx, responderID, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) map[string]interface{}); ok {
		r0 = rf(ctx, responderID, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, responderID, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_GetParticipantEligibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantEligibility'
type MockQsAnswerRepository_GetParticipantEligibility_Call struct {
	*mock.Call
}

// GetParticipantEligibility is a helper method to define mock.On call
//   - ctx context.Context
//   - responderID int64
//   - projectID int64
func (_e *MockQsAnswerRepository_Expecter) GetParticipantEligibility(ctx interface{}, responderID interface{}, projectID interface{}) *MockQsAnswerRepository_GetParticipantEligibility_Call {
	return &MockQsAnswerRepository_GetParticipantEligibility_Call{Call: _e.mock.On("GetParticipantEligibility", ctx, responderID, projectID)}
}

func (_c *MockQsAnswerRepository_GetParticipantEligibility_Call) Run(run func(ctx context.Context, responderID int64, projectID int64)) *MockQsAnswerRepository_GetParticipantEligibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockQsAnswerRepository_GetParticipantEligibility_Call) Return(_a0 map[string]interface{}, _a1 error) *MockQsAnswerRepository_GetParticipantEligibility_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_GetParticipantEligibility_Call) RunAndReturn(run func(context.Context, int64, int64) (map[string]interface{}, error)) *MockQsAnswerRepository_GetParticipantEligibility_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTimeSlot provides a mock function with given fields: ctx, timeSlotID
func (_m *MockQsAnswerRepository) ListByTimeSlot(ctx context.Context, timeSlotID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, timeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTimeSlot")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, timeSlotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, timeSlotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, timeSlotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListByTimeSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTimeSlot'
type MockQsAnswerRepository_ListByTimeSlot_Call struct {
	*mock.Call
}

// ListByTimeSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
func (_e *MockQsAnswerRepository_Expecter) ListByTimeSlot(ctx interface{}, timeSlotID interface{}) *MockQsAnswerRepository_ListByTimeSlot_Call {
	return &MockQsAnswerRepository_ListByTimeSlot_Call{Call: _e.mock.On("ListByTimeSlot", ctx, timeSlotID)}
}

func (_c *MockQsAnswerRepository_ListByTimeSlot_Call) Run(run func(ctx context.Context, timeSlotID int64)) *MockQsAnswerRepository_ListByTimeSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListByTimeSlot_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsAnswerRepository_ListByTimeSlot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListByTimeSlot_Call) RunAndReturn(run func(context.Context, int64) ([]map[string]interface{}, error)) *MockQsAnswerRepository_ListByTimeSlot_Call {
	_c.Call.Return(run)
	return _c
}

// ListCommunicationTemplates provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListCommunicationTemplates(ctx context.Context) ([]qs.CommunicationTemplate, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCommunicationTemplates")
	}

	var r0 []qs.CommunicationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]qs.CommunicationTemplate, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []qs.CommunicationTemplate); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.CommunicationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListCommunicationTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommunicationTemplates'
type MockQsAnswerRepository_ListCommunicationTemplates_Call struct {
	*mock.Call
}

// ListCommunicationTemplates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListCommunicationTemplates(ctx interface{}) *MockQsAnswerRepository_ListCommunicationTemplates_Call {
	return &MockQsAnswerRepository_ListCommunicationTemplates_Call{Call: _e.mock.On("ListCommunicationTemplates", ctx)}
}

func (_c *MockQsAnswerRepository_ListCommunicationTemplates_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListCommunicationTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListCommunicationTemplates_Call) Return(_a0 []qs.CommunicationTemplate, _a1 error) *MockQsAnswerRepository_ListCommunicationTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListCommunicationTemplates_Call) RunAndReturn(run func(context.Context) ([]qs.CommunicationTemplate, error)) *MockQsAnswerRepository_ListCommunicationTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// ListExternalClients provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListExternalClients(ctx context.Context) ([]qs.ExternalClient, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListExternalClients")
	}

	var r0 []qs.ExternalClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]qs.ExternalClient, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []qs.ExternalClient); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.ExternalClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListExternalClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExternalClients'
type MockQsAnswerRepository_ListExternalClients_Call struct {
	*mock.Call
}

// ListExternalClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListExternalClients(ctx interface{}) *MockQsAnswerRepository_ListExternalClients_Call {
	return &MockQsAnswerRepository_ListExternalClients_Call{Call: _e.mock.On("ListExternalClients", ctx)}
}

func (_c *MockQsAnswerRepository_ListExternalClients_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListExternalClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListExternalClients_Call) Return(_a0 []qs.ExternalClient, _a1 error) *MockQsAnswerRepository_ListExternalClients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListExternalClients_Call) RunAndReturn(run func(context.Context) ([]qs.ExternalClient, error)) *MockQsAnswerRepository_ListExternalClients_Call {
	_c.Call.Return(run)
	return _c
}

// ListHonorariumAmounts provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListHonorariumAmounts(ctx context.Context) ([]qs.HonorariumAmount, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListHonorariumAmounts")
	}

	var r0 []qs.HonorariumAmount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]qs.HonorariumAmount, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []qs.HonorariumAmount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.HonorariumAmount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListHonorariumAmounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHonorariumAmounts'
type MockQsAnswerRepository_ListHonorariumAmounts_Call struct {
	*mock.Call
}

// ListHonorariumAmounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListHonorariumAmounts(ctx interface{}) *MockQsAnswerRepository_ListHonorariumAmounts_Call {
	return &MockQsAnswerRepository_ListHonorariumAmounts_Call{Call: _e.mock.On("ListHonorariumAmounts", ctx)}
}

func (_c *MockQsAnswerRepository_ListHonorariumAmounts_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListHonorariumAmounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListHonorariumAmounts_Call) Return(_a0 []qs.HonorariumAmount, _a1 error) *MockQsAnswerRepository_ListHonorariumAmounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListHonorariumAmounts_Call) RunAndReturn(run func(context.Context) ([]qs.HonorariumAmount, error)) *MockQsAnswerRepository_ListHonorariumAmounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListHonorariumReasons provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListHonorariumReasons(ctx context.Context) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListHonorariumReasons")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListHonorariumReasons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHonorariumReasons'
type MockQsAnswerRepository_ListHonorariumReasons_Call struct {
	*mock.Call
}

// ListHonorariumReasons is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListHonorariumReasons(ctx interface{}) *MockQsAnswerRepository_ListHonorariumReasons_Call {
	return &MockQsAnswerRepository_ListHonorariumReasons_Call{Call: _e.mock.On("ListHonorariumReasons", ctx)}
}

func (_c *MockQsAnswerRepository_ListHonorariumReasons_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListHonorariumReasons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListHonorariumReasons_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsAnswerRepository_ListHonorariumReasons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListHonorariumReasons_Call) RunAndReturn(run func(context.Context) ([]map[string]interface{}, error)) *MockQsAnswerRepository_ListHonorariumReasons_Call {
	_c.Call.Return(run)
	return _c
}

// ListInterviewPaymentStatuses provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListInterviewPaymentStatuses(ctx context.Context) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListInterviewPaymentStatuses")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListInterviewPaymentStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInterviewPaymentStatuses'
type MockQsAnswerRepository_ListInterviewPaymentStatuses_Call struct {
	*mock.Call
}

// ListInterviewPaymentStatuses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListInterviewPaymentStatuses(ctx interface{}) *MockQsAnswerRepository_ListInterviewPaymentStatuses_Call {
	return &MockQsAnswerRepository_ListInterviewPaymentStatuses_Call{Call: _e.mock.On("ListInterviewPaymentStatuses", ctx)}
}

func (_c *MockQsAnswerRepository_ListInterviewPaymentStatuses_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListInterviewPaymentStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListInterviewPaymentStatuses_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsAnswerRepository_ListInterviewPaymentStatuses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListInterviewPaymentStatuses_Call) RunAndReturn(run func(context.Context) ([]map[string]interface{}, error)) *MockQsAnswerRepository_ListInterviewPaymentStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// ListLocales provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListLocales(ctx context.Context) ([]qs.LanguageLocalisation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListLocales")
	}

	var r0 []qs.LanguageLocalisation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]qs.LanguageLocalisation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []qs.LanguageLocalisation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.LanguageLocalisation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListLocales_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLocales'
type MockQsAnswerRepository_ListLocales_Call struct {
	*mock.Call
}

// ListLocales is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListLocales(ctx interface{}) *MockQsAnswerRepository_ListLocales_Call {
	return &MockQsAnswerRepository_ListLocales_Call{Call: _e.mock.On("ListLocales", ctx)}
}

func (_c *MockQsAnswerRepository_ListLocales_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListLocales_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListLocales_Call) Return(_a0 []qs.LanguageLocalisation, _a1 error) *MockQsAnswerRepository_ListLocales_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListLocales_Call) RunAndReturn(run func(context.Context) ([]qs.LanguageLocalisation, error)) *MockQsAnswerRepository_ListLocales_Call {
	_c.Call.Return(run)
	return _c
}

// ListNativeSurveysByProject provides a mock function with given fields: ctx, projectID
func (_m *MockQsAnswerRepository) ListNativeSurveysByProject(ctx context.Context, projectID int64) ([]qs.NativeSurvey, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListNativeSurveysByProject")
	}

	var r0 []qs.NativeSurvey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]qs.NativeSurvey, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []qs.NativeSurvey); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.NativeSurvey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListNativeSurveysByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNativeSurveysByProject'
type MockQsAnswerRepository_ListNativeSurveysByProject_Call struct {
	*mock.Call
}

// ListNativeSurveysByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockQsAnswerRepository_Expecter) ListNativeSurveysByProject(ctx interface{}, projectID interface{}) *MockQsAnswerRepository_ListNativeSurveysByProject_Call {
	return &MockQsAnswerRepository_ListNativeSurveysByProject_Call{Call: _e.mock.On("ListNativeSurveysByProject", ctx, projectID)}
}

func (_c *MockQsAnswerRepository_ListNativeSurveysByProject_Call) Run(run func(ctx context.Context, projectID int64)) *MockQsAnswerRepository_ListNativeSurveysByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListNativeSurveysByProject_Call) Return(_a0 []qs.NativeSurvey, _a1 error) *MockQsAnswerRepository_ListNativeSurveysByProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListNativeSurveysByProject_Call) RunAndReturn(run func(context.Context, int64) ([]qs.NativeSurvey, error)) *MockQsAnswerRepository_ListNativeSurveysByProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaymentHistory provides a mock function with given fields: ctx, timeSlotID
func (_m *MockQsAnswerRepository) ListPaymentHistory(ctx context.Context, timeSlotID int64) ([]qs.PaymentHistory, error) {
	ret := _m.Called(ctx, timeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymentHistory")
	}

	var r0 []qs.PaymentHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]qs.PaymentHistory, error)); ok {
		return rf(ctx, timeSlotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []qs.PaymentHistory); ok {
		r0 = rf(ctx, timeSlotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.PaymentHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, timeSlotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListPaymentHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaymentHistory'
type MockQsAnswerRepository_ListPaymentHistory_Call struct {
	*mock.Call
}

// ListPaymentHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
func (_e *MockQsAnswerRepository_Expecter) ListPaymentHistory(ctx interface{}, timeSlotID interface{}) *MockQsAnswerRepository_ListPaymentHistory_Call {
	return &MockQsAnswerRepository_ListPaymentHistory_Call{Call: _e.mock.On("ListPaymentHistory", ctx, timeSlotID)}
}

func (_c *MockQsAnswerRepository_ListPaymentHistory_Call) Run(run func(ctx context.Context, timeSlotID int64)) *MockQsAnswerRepository_ListPaymentHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListPaymentHistory_Call) Return(_a0 []qs.PaymentHistory, _a1 error) *MockQsAnswerRepository_ListPaymentHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListPaymentHistory_Call) RunAndReturn(run func(context.Context, int64) ([]qs.PaymentHistory, error)) *MockQsAnswerRepository_ListPaymentHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectsUsers provides a mock function with given fields: ctx, projectID
func (_m *MockQsAnswerRepository) ListProjectsUsers(ctx context.Context, projectID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectsUsers")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListProjectsUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectsUsers'
type MockQsAnswerRepository_ListProjectsUsers_Call struct {
	*mock.Call
}

// ListProjectsUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockQsAnswerRepository_Expecter) ListProjectsUsers(ctx interface{}, projectID interface{}) *MockQsAnswerRepository_ListProjectsUsers_Call {
	return &MockQsAnswerRepository_ListProjectsUsers_Call{Call: _e.mock.On("ListProjectsUsers", ctx, projectID)}
}

func (_c *MockQsAnswerRepository_ListProjectsUsers_Call) Run(run func(ctx context.Context, projectID int64)) *MockQsAnswerRepository_ListProjectsUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListProjectsUsers_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsAnswerRepository_ListProjectsUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListProjectsUsers_Call) RunAndReturn(run func(context.Context, int64) ([]map[string]interface{}, error)) *MockQsAnswerRepository_ListProjectsUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ListSalesforceAccounts provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListSalesforceAccounts(ctx context.Context) ([]qs.QSSalesforceAccount, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSalesforceAccounts")
	}

	var r0 []qs.QSSalesforceAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]qs.QSSalesforceAccount, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []qs.QSSalesforceAccount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.QSSalesforceAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListSalesforceAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSalesforceAccounts'
type MockQsAnswerRepository_ListSalesforceAccounts_Call struct {
	*mock.Call
}

// ListSalesforceAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListSalesforceAccounts(ctx interface{}) *MockQsAnswerRepository_ListSalesforceAccounts_Call {
	return &MockQsAnswerRepository_ListSalesforceAccounts_Call{Call: _e.mock.On("ListSalesforceAccounts", ctx)}
}

func (_c *MockQsAnswerRepository_ListSalesforceAccounts_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListSalesforceAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListSalesforceAccounts_Call) Return(_a0 []qs.QSSalesforceAccount, _a1 error) *MockQsAnswerRepository_ListSalesforceAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListSalesforceAccounts_Call) RunAndReturn(run func(context.Context) ([]qs.QSSalesforceAccount, error)) *MockQsAnswerRepository_ListSalesforceAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListSalesforceProjects provides a mock function with given fields: ctx
func (_m *MockQsAnswerRepository) ListSalesforceProjects(ctx context.Context) ([]qs.QSSalesforceProject, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSalesforceProjects")
	}

	var r0 []qs.QSSalesforceProject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]qs.QSSalesforceProject, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []qs.QSSalesforceProject); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.QSSalesforceProject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListSalesforceProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSalesforceProjects'
type MockQsAnswerRepository_ListSalesforceProjects_Call struct {
	*mock.Call
}

// ListSalesforceProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQsAnswerRepository_Expecter) ListSalesforceProjects(ctx interface{}) *MockQsAnswerRepository_ListSalesforceProjects_Call {
	return &MockQsAnswerRepository_ListSalesforceProjects_Call{Call: _e.mock.On("ListSalesforceProjects", ctx)}
}

func (_c *MockQsAnswerRepository_ListSalesforceProjects_Call) Run(run func(ctx context.Context)) *MockQsAnswerRepository_ListSalesforceProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListSalesforceProjects_Call) Return(_a0 []qs.QSSalesforceProject, _a1 error) *MockQsAnswerRepository_ListSalesforceProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListSalesforceProjects_Call) RunAndReturn(run func(context.Context) ([]qs.QSSalesforceProject, error)) *MockQsAnswerRepository_ListSalesforceProjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopics provides a mock function with given fields: ctx, projectID
func (_m *MockQsAnswerRepository) ListTopics(ctx context.Context, projectID int64) ([]qs.Topic, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListTopics")
	}

	var r0 []qs.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]qs.Topic, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []qs.Topic); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qs.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsAnswerRepository_ListTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopics'
type MockQsAnswerRepository_ListTopics_Call struct {
	*mock.Call
}

// ListTopics is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockQsAnswerRepository_Expecter) ListTopics(ctx interface{}, projectID interface{}) *MockQsAnswerRepository_ListTopics_Call {
	return &MockQsAnswerRepository_ListTopics_Call{Call: _e.mock.On("ListTopics", ctx, projectID)}
}

func (_c *MockQsAnswerRepository_ListTopics_Call) Run(run func(ctx context.Context, projectID int64)) *MockQsAnswerRepository_ListTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsAnswerRepository_ListTopics_Call) Return(_a0 []qs.Topic, _a1 error) *MockQsAnswerRepository_ListTopics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsAnswerRepository_ListTopics_Call) RunAndReturn(run func(context.Context, int64) ([]qs.Topic, error)) *MockQsAnswerRepository_ListTopics_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTopicTranslation provides a mock function with given fields: ctx, projectID, topicID, languageCode, translatedName
func (_m *MockQsAnswerRepository) UpdateTopicTranslation(ctx context.Context, projectID int64, topicID int64, languageCode string, translatedName string) error {
	ret := _m.Called(ctx, projectID, topicID, languageCode, translatedName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTopicTranslation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) error); ok {
		r0 = rf(ctx, projectID, topicID, languageCode, translatedName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsAnswerRepository_UpdateTopicTranslation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTopicTranslation'
type MockQsAnswerRepository_UpdateTopicTranslation_Call struct {
	*mock.Call
}

// UpdateTopicTranslation is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - topicID int64
//   - languageCode string
//   - translatedName string
func (_e *MockQsAnswerRepository_Expecter) UpdateTopicTranslation(ctx interface{}, projectID interface{}, topicID interface{}, languageCode interface{}, translatedName interface{}) *MockQsAnswerRepository_UpdateTopicTranslation_Call {
	return &MockQsAnswerRepository_UpdateTopicTranslation_Call{Call: _e.mock.On("UpdateTopicTranslation", ctx, projectID, topicID, languageCode, translatedName)}
}

func (_c *MockQsAnswerRepository_UpdateTopicTranslation_Call) Run(run func(ctx context.Context, projectID int64, topicID int64, languageCode string, translatedName string)) *MockQsAnswerRepository_UpdateTopicTranslation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockQsAnswerRepository_UpdateTopicTranslation_Call) Return(_a0 error) *MockQsAnswerRepository_UpdateTopicTranslation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsAnswerRepository_UpdateTopicTranslation_Call) RunAndReturn(run func(context.Context, int64, int64, string, string) error) *MockQsAnswerRepository_UpdateTopicTranslation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQsAnswerRepository creates a new instance of MockQsAnswerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQsAnswerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQsAnswerRepository {
	mock := &MockQsAnswerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
