// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	iris "github.com/InCrowd/unified-qual-api/internal/repository/iris"
)

// MockIrisProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockIrisProjectRepository struct {
	mock.Mock
}

type MockIrisProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIrisProjectRepository) EXPECT() *MockIrisProjectRepository_Expecter {
	return &MockIrisProjectRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockIrisProjectRepository) Create(ctx context.Context, p *iris.Project) (int64, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *iris.Project) (int64, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *iris.Project) int64); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *iris.Project) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisProjectRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIrisProjectRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *iris.Project
func (_e *MockIrisProjectRepository_Expecter) Create(ctx interface{}, p interface{}) *MockIrisProjectRepository_Create_Call {
	return &MockIrisProjectRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockIrisProjectRepository_Create_Call) Run(run func(ctx context.Context, p *iris.Project)) *MockIrisProjectRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*iris.Project))
	})
	return _c
}

func (_c *MockIrisProjectRepository_Create_Call) Return(_a0 int64, _a1 error) *MockIrisProjectRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisProjectRepository_Create_Call) RunAndReturn(run func(context.Context, *iris.Project) (int64, error)) *MockIrisProjectRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIrisProjectRepository) GetByID(ctx context.Context, id int64) (*iris.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *iris.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*iris.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *iris.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iris.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisProjectRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIrisProjectRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIrisProjectRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIrisProjectRepository_GetByID_Call {
	return &MockIrisProjectRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIrisProjectRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockIrisProjectRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIrisProjectRepository_GetByID_Call) Return(_a0 *iris.Project, _a1 error) *MockIrisProjectRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisProjectRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*iris.Project, error)) *MockIrisProjectRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, pageSize, statusID, search
func (_m *MockIrisProjectRepository) List(ctx context.Context, page int, pageSize int, statusID *int, search string) ([]iris.ProjectListRow, int, error) {
	ret := _m.Called(ctx, page, pageSize, statusID, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []iris.ProjectListRow
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *int, string) ([]iris.ProjectListRow, int, error)); ok {
		return rf(ctx, page, pageSize, statusID, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *int, string) []iris.ProjectListRow); ok {
		r0 = rf(ctx, page, pageSize, statusID, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.ProjectListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *int, string) int); ok {
		r1 = rf(ctx, page, pageSize, statusID, search)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, *int, string) error); ok {
		r2 = rf(ctx, page, pageSize, statusID, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIrisProjectRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIrisProjectRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
//   - statusID *int
//   - search string
func (_e *MockIrisProjectRepository_Expecter) List(ctx interface{}, page interface{}, pageSize interface{}, statusID interface{}, search interface{}) *MockIrisProjectRepository_List_Call {
	return &MockIrisProjectRepository_List_Call{Call: _e.mock.On("List", ctx, page, pageSize, statusID, search)}
}

func (_c *MockIrisProjectRepository_List_Call) Run(run func(ctx context.Context, page int, pageSize int, statusID *int, search string)) *MockIrisProjectRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*int), args[4].(string))
	})
	return _c
}

func (_c *MockIrisProjectRepository_List_Call) Return(_a0 []iris.ProjectListRow, _a1 int, _a2 error) *MockIrisProjectRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIrisProjectRepository_List_Call) RunAndReturn(run func(context.Context, int, int, *int, string) ([]iris.ProjectListRow, int, error)) *MockIrisProjectRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, fields
func (_m *MockIrisProjectRepository) Update(ctx context.Context, id int64, fields map[string]interface{}) error {
	ret := _m.Called(ctx, id, fields)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisProjectRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIrisProjectRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - fields map[string]interface{}
func (_e *MockIrisProjectRepository_Expecter) Update(ctx interface{}, id interface{}, fields interface{}) *MockIrisProjectRepository_Update_Call {
	return &MockIrisProjectRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, fields)}
}

func (_c *MockIrisProjectRepository_Update_Call) Run(run func(ctx context.Context, id int64, fields map[string]interface{})) *MockIrisProjectRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIrisProjectRepository_Update_Call) Return(_a0 error) *MockIrisProjectRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisProjectRepository_Update_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *MockIrisProjectRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIrisProjectRepository creates a new instance of MockIrisProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIrisProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIrisProjectRepository {
	mock := &MockIrisProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
