// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	qs "github.com/InCrowd/unified-qual-api/internal/repository/qs"
)

// MockQsConferenceRepository is an autogenerated mock type for the ConferenceRepository type
type MockQsConferenceRepository struct {
	mock.Mock
}

type MockQsConferenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQsConferenceRepository) EXPECT() *MockQsConferenceRepository_Expecter {
	return &MockQsConferenceRepository_Expecter{mock: &_m.Mock}
}

// AddConferenceLinkMRA provides a mock function with given fields: ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation
func (_m *MockQsConferenceRepository) AddConferenceLinkMRA(ctx context.Context, projectID int64, participantGroupID int64, userID int64, conferenceLink string, meetingInformation [][]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation)

	if len(ret) == 0 {
		panic("no return value specified for AddConferenceLinkMRA")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, string, [][]interface{}) (map[string]interface{}, error)); ok {
		return rf(ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, string, [][]interface{}) map[string]interface{}); ok {
		r0 = rf(ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64, string, [][]interface{}) error); ok {
		r1 = rf(ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_AddConferenceLinkMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConferenceLinkMRA'
type MockQsConferenceRepository_AddConferenceLinkMRA_Call struct {
	*mock.Call
}

// AddConferenceLinkMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - participantGroupID int64
//   - userID int64
//   - conferenceLink string
//   - meetingInformation [][]interface{}
func (_e *MockQsConferenceRepository_Expecter) AddConferenceLinkMRA(ctx interface{}, projectID interface{}, participantGroupID interface{}, userID interface{}, conferenceLink interface{}, meetingInformation interface{}) *MockQsConferenceRepository_AddConferenceLinkMRA_Call {
	return &MockQsConferenceRepository_AddConferenceLinkMRA_Call{Call: _e.mock.On("AddConferenceLinkMRA", ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation)}
}

func (_c *MockQsConferenceRepository_AddConferenceLinkMRA_Call) Run(run func(ctx context.Context, projectID int64, participantGroupID int64, userID int64, conferenceLink string, meetingInformation [][]interface{})) *MockQsConferenceRepository_AddConferenceLinkMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64), args[4].(string), args[5].([][]interface{}))
	})
	return _c
}

func (_c *MockQsConferenceRepository_AddConferenceLinkMRA_Call) Return(_a0 map[string]interface{}, _a1 error) *MockQsConferenceRepository_AddConferenceLinkMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_AddConferenceLinkMRA_Call) RunAndReturn(run func(context.Context, int64, int64, int64, string, [][]interface{}) (map[string]interface{}, error)) *MockQsConferenceRepository_AddConferenceLinkMRA_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConferenceLink provides a mock function with given fields: ctx, timeSlotID, projectID, conferenceHash
func (_m *MockQsConferenceRepository) CreateConferenceLink(ctx context.Context, timeSlotID int64, projectID int64, conferenceHash string) (int64, error) {
	ret := _m.Called(ctx, timeSlotID, projectID, conferenceHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateConferenceLink")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) (int64, error)); ok {
		return rf(ctx, timeSlotID, projectID, conferenceHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) int64); ok {
		r0 = rf(ctx, timeSlotID, projectID, conferenceHash)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string) error); ok {
		r1 = rf(ctx, timeSlotID, projectID, conferenceHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_CreateConferenceLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConferenceLink'
type MockQsConferenceRepository_CreateConferenceLink_Call struct {
	*mock.Call
}

// CreateConferenceLink is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
//   - projectID int64
//   - conferenceHash string
func (_e *MockQsConferenceRepository_Expecter) CreateConferenceLink(ctx interface{}, timeSlotID interface{}, projectID interface{}, conferenceHash interface{}) *MockQsConferenceRepository_CreateConferenceLink_Call {
	return &MockQsConferenceRepository_CreateConferenceLink_Call{Call: _e.mock.On("CreateConferenceLink", ctx, timeSlotID, projectID, conferenceHash)}
}

func (_c *MockQsConferenceRepository_CreateConferenceLink_Call) Run(run func(ctx context.Context, timeSlotID int64, projectID int64, conferenceHash string)) *MockQsConferenceRepository_CreateConferenceLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockQsConferenceRepository_CreateConferenceLink_Call) Return(_a0 int64, _a1 error) *MockQsConferenceRepository_CreateConferenceLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_CreateConferenceLink_Call) RunAndReturn(run func(context.Context, int64, int64, string) (int64, error)) *MockQsConferenceRepository_CreateConferenceLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendeesByMeetingID provides a mock function with given fields: ctx, meetingID
func (_m *MockQsConferenceRepository) GetAttendeesByMeetingID(ctx context.Context, meetingID string) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, meetingID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendeesByMeetingID")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]map[string]interface{}, error)); ok {
		return rf(ctx, meetingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []map[string]interface{}); ok {
		r0 = rf(ctx, meetingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, meetingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetAttendeesByMeetingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendeesByMeetingID'
type MockQsConferenceRepository_GetAttendeesByMeetingID_Call struct {
	*mock.Call
}

// GetAttendeesByMeetingID is a helper method to define mock.On call
//   - ctx context.Context
//   - meetingID string
func (_e *MockQsConferenceRepository_Expecter) GetAttendeesByMeetingID(ctx interface{}, meetingID interface{}) *MockQsConferenceRepository_GetAttendeesByMeetingID_Call {
	return &MockQsConferenceRepository_GetAttendeesByMeetingID_Call{Call: _e.mock.On("GetAttendeesByMeetingID", ctx, meetingID)}
}

func (_c *MockQsConferenceRepository_GetAttendeesByMeetingID_Call) Run(run func(ctx context.Context, meetingID string)) *MockQsConferenceRepository_GetAttendeesByMeetingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetAttendeesByMeetingID_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsConferenceRepository_GetAttendeesByMeetingID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetAttendeesByMeetingID_Call) RunAndReturn(run func(context.Context, string) ([]map[string]interface{}, error)) *MockQsConferenceRepository_GetAttendeesByMeetingID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, hash
func (_m *MockQsConferenceRepository) GetByHash(ctx context.Context, hash string) (*qs.ConferenceInvitation, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *qs.ConferenceInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*qs.ConferenceInvitation, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *qs.ConferenceInvitation); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qs.ConferenceInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockQsConferenceRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockQsConferenceRepository_Expecter) GetByHash(ctx interface{}, hash interface{}) *MockQsConferenceRepository_GetByHash_Call {
	return &MockQsConferenceRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, hash)}
}

func (_c *MockQsConferenceRepository_GetByHash_Call) Run(run func(ctx context.Context, hash string)) *MockQsConferenceRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetByHash_Call) Return(_a0 *qs.ConferenceInvitation, _a1 error) *MockQsConferenceRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (*qs.ConferenceInvitation, error)) *MockQsConferenceRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetConferenceLinkByProjectMRA provides a mock function with given fields: ctx, projectID
func (_m *MockQsConferenceRepository) GetConferenceLinkByProjectMRA(ctx context.Context, projectID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetConferenceLinkByProjectMRA")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConferenceLinkByProjectMRA'
type MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call struct {
	*mock.Call
}

// GetConferenceLinkByProjectMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockQsConferenceRepository_Expecter) GetConferenceLinkByProjectMRA(ctx interface{}, projectID interface{}) *MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call {
	return &MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call{Call: _e.mock.On("GetConferenceLinkByProjectMRA", ctx, projectID)}
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call) Run(run func(ctx context.Context, projectID int64)) *MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call) RunAndReturn(run func(context.Context, int64) ([]map[string]interface{}, error)) *MockQsConferenceRepository_GetConferenceLinkByProjectMRA_Call {
	_c.Call.Return(run)
	return _c
}

// GetConferenceLinkByTimeSlotID provides a mock function with given fields: ctx, timeSlotID
func (_m *MockQsConferenceRepository) GetConferenceLinkByTimeSlotID(ctx context.Context, timeSlotID int64) (map[string]interface{}, error) {
	ret := _m.Called(ctx, timeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for GetConferenceLinkByTimeSlotID")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[string]interface{}, error)); ok {
		return rf(ctx, timeSlotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[string]interface{}); ok {
		r0 = rf(ctx, timeSlotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, timeSlotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConferenceLinkByTimeSlotID'
type MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call struct {
	*mock.Call
}

// GetConferenceLinkByTimeSlotID is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
func (_e *MockQsConferenceRepository_Expecter) GetConferenceLinkByTimeSlotID(ctx interface{}, timeSlotID interface{}) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call {
	return &MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call{Call: _e.mock.On("GetConferenceLinkByTimeSlotID", ctx, timeSlotID)}
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call) Run(run func(ctx context.Context, timeSlotID int64)) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call) Return(_a0 map[string]interface{}, _a1 error) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call) RunAndReturn(run func(context.Context, int64) (map[string]interface{}, error)) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConferenceLinkByTimeSlotMRA provides a mock function with given fields: ctx, timeSlotID
func (_m *MockQsConferenceRepository) GetConferenceLinkByTimeSlotMRA(ctx context.Context, timeSlotID int64) (map[string]interface{}, error) {
	ret := _m.Called(ctx, timeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for GetConferenceLinkByTimeSlotMRA")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[string]interface{}, error)); ok {
		return rf(ctx, timeSlotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[string]interface{}); ok {
		r0 = rf(ctx, timeSlotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, timeSlotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConferenceLinkByTimeSlotMRA'
type MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call struct {
	*mock.Call
}

// GetConferenceLinkByTimeSlotMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
func (_e *MockQsConferenceRepository_Expecter) GetConferenceLinkByTimeSlotMRA(ctx interface{}, timeSlotID interface{}) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call {
	return &MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call{Call: _e.mock.On("GetConferenceLinkByTimeSlotMRA", ctx, timeSlotID)}
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call) Run(run func(ctx context.Context, timeSlotID int64)) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call) Return(_a0 map[string]interface{}, _a1 error) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call) RunAndReturn(run func(context.Context, int64) (map[string]interface{}, error)) *MockQsConferenceRepository_GetConferenceLinkByTimeSlotMRA_Call {
	_c.Call.Return(run)
	return _c
}

// GetExistingMeetingLanguagesMRA provides a mock function with given fields: ctx, projectID
func (_m *MockQsConferenceRepository) GetExistingMeetingLanguagesMRA(ctx context.Context, projectID int64) (map[string]bool, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetExistingMeetingLanguagesMRA")
	}

	var r0 map[string]bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[string]bool, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[string]bool); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExistingMeetingLanguagesMRA'
type MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call struct {
	*mock.Call
}

// GetExistingMeetingLanguagesMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockQsConferenceRepository_Expecter) GetExistingMeetingLanguagesMRA(ctx interface{}, projectID interface{}) *MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call {
	return &MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call{Call: _e.mock.On("GetExistingMeetingLanguagesMRA", ctx, projectID)}
}

func (_c *MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call) Run(run func(ctx context.Context, projectID int64)) *MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call) Return(_a0 map[string]bool, _a1 error) *MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call) RunAndReturn(run func(context.Context, int64) (map[string]bool, error)) *MockQsConferenceRepository_GetExistingMeetingLanguagesMRA_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeetingMetadata provides a mock function with given fields: ctx, conferenceHash
func (_m *MockQsConferenceRepository) GetMeetingMetadata(ctx context.Context, conferenceHash string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, conferenceHash)

	if len(ret) == 0 {
		panic("no return value specified for GetMeetingMetadata")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, conferenceHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, conferenceHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, conferenceHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetMeetingMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeetingMetadata'
type MockQsConferenceRepository_GetMeetingMetadata_Call struct {
	*mock.Call
}

// GetMeetingMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - conferenceHash string
func (_e *MockQsConferenceRepository_Expecter) GetMeetingMetadata(ctx interface{}, conferenceHash interface{}) *MockQsConferenceRepository_GetMeetingMetadata_Call {
	return &MockQsConferenceRepository_GetMeetingMetadata_Call{Call: _e.mock.On("GetMeetingMetadata", ctx, conferenceHash)}
}

func (_c *MockQsConferenceRepository_GetMeetingMetadata_Call) Run(run func(ctx context.Context, conferenceHash string)) *MockQsConferenceRepository_GetMeetingMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetMeetingMetadata_Call) Return(_a0 map[string]interface{}, _a1 error) *MockQsConferenceRepository_GetMeetingMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetMeetingMetadata_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *MockQsConferenceRepository_GetMeetingMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipants provides a mock function with given fields: ctx, timeSlotID
func (_m *MockQsConferenceRepository) GetParticipants(ctx context.Context, timeSlotID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, timeSlotID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipants")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, timeSlotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, timeSlotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, timeSlotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipants'
type MockQsConferenceRepository_GetParticipants_Call struct {
	*mock.Call
}

// GetParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
func (_e *MockQsConferenceRepository_Expecter) GetParticipants(ctx interface{}, timeSlotID interface{}) *MockQsConferenceRepository_GetParticipants_Call {
	return &MockQsConferenceRepository_GetParticipants_Call{Call: _e.mock.On("GetParticipants", ctx, timeSlotID)}
}

func (_c *MockQsConferenceRepository_GetParticipants_Call) Run(run func(ctx context.Context, timeSlotID int64)) *MockQsConferenceRepository_GetParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetParticipants_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsConferenceRepository_GetParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetParticipants_Call) RunAndReturn(run func(context.Context, int64) ([]map[string]interface{}, error)) *MockQsConferenceRepository_GetParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingTimeSlotsCountMRA provides a mock function with given fields: ctx, projectID
func (_m *MockQsConferenceRepository) GetPendingTimeSlotsCountMRA(ctx context.Context, projectID int64) (int64, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingTimeSlotsCountMRA")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingTimeSlotsCountMRA'
type MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call struct {
	*mock.Call
}

// GetPendingTimeSlotsCountMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockQsConferenceRepository_Expecter) GetPendingTimeSlotsCountMRA(ctx interface{}, projectID interface{}) *MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call {
	return &MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call{Call: _e.mock.On("GetPendingTimeSlotsCountMRA", ctx, projectID)}
}

func (_c *MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call) Run(run func(ctx context.Context, projectID int64)) *MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call) Return(_a0 int64, _a1 error) *MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockQsConferenceRepository_GetPendingTimeSlotsCountMRA_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, conferenceHash, pin
func (_m *MockQsConferenceRepository) Login(ctx context.Context, conferenceHash string, pin string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, conferenceHash, pin)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string]interface{}, error)); ok {
		return rf(ctx, conferenceHash, pin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string]interface{}); ok {
		r0 = rf(ctx, conferenceHash, pin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, conferenceHash, pin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsConferenceRepository_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockQsConferenceRepository_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - conferenceHash string
//   - pin string
func (_e *MockQsConferenceRepository_Expecter) Login(ctx interface{}, conferenceHash interface{}, pin interface{}) *MockQsConferenceRepository_Login_Call {
	return &MockQsConferenceRepository_Login_Call{Call: _e.mock.On("Login", ctx, conferenceHash, pin)}
}

func (_c *MockQsConferenceRepository_Login_Call) Run(run func(ctx context.Context, conferenceHash string, pin string)) *MockQsConferenceRepository_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockQsConferenceRepository_Login_Call) Return(_a0 map[string]interface{}, _a1 error) *MockQsConferenceRepository_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsConferenceRepository_Login_Call) RunAndReturn(run func(context.Context, string, string) (map[string]interface{}, error)) *MockQsConferenceRepository_Login_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConferenceLink provides a mock function with given fields: ctx, timeSlotID, conferenceHash, pin
func (_m *MockQsConferenceRepository) UpdateConferenceLink(ctx context.Context, timeSlotID int64, conferenceHash string, pin string) error {
	ret := _m.Called(ctx, timeSlotID, conferenceHash, pin)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConferenceLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, timeSlotID, conferenceHash, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsConferenceRepository_UpdateConferenceLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConferenceLink'
type MockQsConferenceRepository_UpdateConferenceLink_Call struct {
	*mock.Call
}

// UpdateConferenceLink is a helper method to define mock.On call
//   - ctx context.Context
//   - timeSlotID int64
//   - conferenceHash string
//   - pin string
func (_e *MockQsConferenceRepository_Expecter) UpdateConferenceLink(ctx interface{}, timeSlotID interface{}, conferenceHash interface{}, pin interface{}) *MockQsConferenceRepository_UpdateConferenceLink_Call {
	return &MockQsConferenceRepository_UpdateConferenceLink_Call{Call: _e.mock.On("UpdateConferenceLink", ctx, timeSlotID, conferenceHash, pin)}
}

func (_c *MockQsConferenceRepository_UpdateConferenceLink_Call) Run(run func(ctx context.Context, timeSlotID int64, conferenceHash string, pin string)) *MockQsConferenceRepository_UpdateConferenceLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockQsConferenceRepository_UpdateConferenceLink_Call) Return(_a0 error) *MockQsConferenceRepository_UpdateConferenceLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsConferenceRepository_UpdateConferenceLink_Call) RunAndReturn(run func(context.Context, int64, string, string) error) *MockQsConferenceRepository_UpdateConferenceLink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConferenceLinkMRA provides a mock function with given fields: ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation, existingLangs
func (_m *MockQsConferenceRepository) UpdateConferenceLinkMRA(ctx context.Context, projectID int64, participantGroupID int64, userID int64, conferenceLink string, meetingInformation [][]interface{}, existingLangs map[string]bool) error {
	ret := _m.Called(ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation, existingLangs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConferenceLinkMRA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, string, [][]interface{}, map[string]bool) error); ok {
		r0 = rf(ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation, existingLangs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsConferenceRepository_UpdateConferenceLinkMRA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConferenceLinkMRA'
type MockQsConferenceRepository_UpdateConferenceLinkMRA_Call struct {
	*mock.Call
}

// UpdateConferenceLinkMRA is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - participantGroupID int64
//   - userID int64
//   - conferenceLink string
//   - meetingInformation [][]interface{}
//   - existingLangs map[string]bool
func (_e *MockQsConferenceRepository_Expecter) UpdateConferenceLinkMRA(ctx interface{}, projectID interface{}, participantGroupID interface{}, userID interface{}, conferenceLink interface{}, meetingInformation interface{}, existingLangs interface{}) *MockQsConferenceRepository_UpdateConferenceLinkMRA_Call {
	return &MockQsConferenceRepository_UpdateConferenceLinkMRA_Call{Call: _e.mock.On("UpdateConferenceLinkMRA", ctx, projectID, participantGroupID, userID, conferenceLink, meetingInformation, existingLangs)}
}

func (_c *MockQsConferenceRepository_UpdateConferenceLinkMRA_Call) Run(run func(ctx context.Context, projectID int64, participantGroupID int64, userID int64, conferenceLink string, meetingInformation [][]interface{}, existingLangs map[string]bool)) *MockQsConferenceRepository_UpdateConferenceLinkMRA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64), args[4].(string), args[5].([][]interface{}), args[6].(map[string]bool))
	})
	return _c
}

func (_c *MockQsConferenceRepository_UpdateConferenceLinkMRA_Call) Return(_a0 error) *MockQsConferenceRepository_UpdateConferenceLinkMRA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsConferenceRepository_UpdateConferenceLinkMRA_Call) RunAndReturn(run func(context.Context, int64, int64, int64, string, [][]interface{}, map[string]bool) error) *MockQsConferenceRepository_UpdateConferenceLinkMRA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecordingStatus provides a mock function with given fields: ctx, meetingID, status, bucket, key
func (_m *MockQsConferenceRepository) UpdateRecordingStatus(ctx context.Context, meetingID string, status string, bucket string, key string) error {
	ret := _m.Called(ctx, meetingID, status, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecordingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, meetingID, status, bucket, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQsConferenceRepository_UpdateRecordingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecordingStatus'
type MockQsConferenceRepository_UpdateRecordingStatus_Call struct {
	*mock.Call
}

// UpdateRecordingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - meetingID string
//   - status string
//   - bucket string
//   - key string
func (_e *MockQsConferenceRepository_Expecter) UpdateRecordingStatus(ctx interface{}, meetingID interface{}, status interface{}, bucket interface{}, key interface{}) *MockQsConferenceRepository_UpdateRecordingStatus_Call {
	return &MockQsConferenceRepository_UpdateRecordingStatus_Call{Call: _e.mock.On("UpdateRecordingStatus", ctx, meetingID, status, bucket, key)}
}

func (_c *MockQsConferenceRepository_UpdateRecordingStatus_Call) Run(run func(ctx context.Context, meetingID string, status string, bucket string, key string)) *MockQsConferenceRepository_UpdateRecordingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockQsConferenceRepository_UpdateRecordingStatus_Call) Return(_a0 error) *MockQsConferenceRepository_UpdateRecordingStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQsConferenceRepository_UpdateRecordingStatus_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockQsConferenceRepository_UpdateRecordingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQsConferenceRepository creates a new instance of MockQsConferenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQsConferenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQsConferenceRepository {
	mock := &MockQsConferenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
