// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	iris "github.com/InCrowd/unified-qual-api/internal/repository/iris"
	mock "github.com/stretchr/testify/mock"
)

// MockIrisUserRepository is an autogenerated mock type for the UserRepository type
type MockIrisUserRepository struct {
	mock.Mock
}

type MockIrisUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIrisUserRepository) EXPECT() *MockIrisUserRepository_Expecter {
	return &MockIrisUserRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockIrisUserRepository) GetByEmail(ctx context.Context, email string) (*iris.ICUserWithRoles, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *iris.ICUserWithRoles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*iris.ICUserWithRoles, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *iris.ICUserWithRoles); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iris.ICUserWithRoles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockIrisUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIrisUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockIrisUserRepository_GetByEmail_Call {
	return &MockIrisUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockIrisUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIrisUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIrisUserRepository_GetByEmail_Call) Return(_a0 *iris.ICUserWithRoles, _a1 error) *MockIrisUserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisUserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*iris.ICUserWithRoles, error)) *MockIrisUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIrisUserRepository) GetByID(ctx context.Context, id int64) (*iris.ICUserWithRoles, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *iris.ICUserWithRoles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*iris.ICUserWithRoles, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *iris.ICUserWithRoles); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iris.ICUserWithRoles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIrisUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIrisUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIrisUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIrisUserRepository_GetByID_Call {
	return &MockIrisUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIrisUserRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockIrisUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIrisUserRepository_GetByID_Call) Return(_a0 *iris.ICUserWithRoles, _a1 error) *MockIrisUserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIrisUserRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*iris.ICUserWithRoles, error)) *MockIrisUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, pageSize, roleID, search
func (_m *MockIrisUserRepository) List(ctx context.Context, page int, pageSize int, roleID *int64, search string) ([]iris.ICUserListRow, int, error) {
	ret := _m.Called(ctx, page, pageSize, roleID, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []iris.ICUserListRow
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *int64, string) ([]iris.ICUserListRow, int, error)); ok {
		return rf(ctx, page, pageSize, roleID, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *int64, string) []iris.ICUserListRow); ok {
		r0 = rf(ctx, page, pageSize, roleID, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iris.ICUserListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *int64, string) int); ok {
		r1 = rf(ctx, page, pageSize, roleID, search)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, *int64, string) error); ok {
		r2 = rf(ctx, page, pageSize, roleID, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIrisUserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIrisUserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
//   - roleID *int64
//   - search string
func (_e *MockIrisUserRepository_Expecter) List(ctx interface{}, page interface{}, pageSize interface{}, roleID interface{}, search interface{}) *MockIrisUserRepository_List_Call {
	return &MockIrisUserRepository_List_Call{Call: _e.mock.On("List", ctx, page, pageSize, roleID, search)}
}

func (_c *MockIrisUserRepository_List_Call) Run(run func(ctx context.Context, page int, pageSize int, roleID *int64, search string)) *MockIrisUserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*int64), args[4].(string))
	})
	return _c
}

func (_c *MockIrisUserRepository_List_Call) Return(_a0 []iris.ICUserListRow, _a1 int, _a2 error) *MockIrisUserRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIrisUserRepository_List_Call) RunAndReturn(run func(context.Context, int, int, *int64, string) ([]iris.ICUserListRow, int, error)) *MockIrisUserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, firstName, lastName, timeZone
func (_m *MockIrisUserRepository) Update(ctx context.Context, id int64, firstName string, lastName string, timeZone string) error {
	ret := _m.Called(ctx, id, firstName, lastName, timeZone)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string) error); ok {
		r0 = rf(ctx, id, firstName, lastName, timeZone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIrisUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIrisUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - firstName string
//   - lastName string
//   - timeZone string
func (_e *MockIrisUserRepository_Expecter) Update(ctx interface{}, id interface{}, firstName interface{}, lastName interface{}, timeZone interface{}) *MockIrisUserRepository_Update_Call {
	return &MockIrisUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, firstName, lastName, timeZone)}
}

func (_c *MockIrisUserRepository_Update_Call) Run(run func(ctx context.Context, id int64, firstName string, lastName string, timeZone string)) *MockIrisUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockIrisUserRepository_Update_Call) Return(_a0 error) *MockIrisUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIrisUserRepository_Update_Call) RunAndReturn(run func(context.Context, int64, string, string, string) error) *MockIrisUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIrisUserRepository creates a new instance of MockIrisUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIrisUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIrisUserRepository {
	mock := &MockIrisUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
