// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQsInterviewsRepository is an autogenerated mock type for the InterviewsRepository type
type MockQsInterviewsRepository struct {
	mock.Mock
}

type MockQsInterviewsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQsInterviewsRepository) EXPECT() *MockQsInterviewsRepository_Expecter {
	return &MockQsInterviewsRepository_Expecter{mock: &_m.Mock}
}

// GetAllInterviewsByOffsetAndActiveTab provides a mock function with given fields: ctx, clientID, externalClientsIDs, projectsIDs, search, offset, activeTab, paymentStatusCode
func (_m *MockQsInterviewsRepository) GetAllInterviewsByOffsetAndActiveTab(ctx context.Context, clientID int64, externalClientsIDs []string, projectsIDs []string, search string, offset int, activeTab string, paymentStatusCode string) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, clientID, externalClientsIDs, projectsIDs, search, offset, activeTab, paymentStatusCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAllInterviewsByOffsetAndActiveTab")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []string, []string, string, int, string, string) ([]map[string]interface{}, error)); ok {
		return rf(ctx, clientID, externalClientsIDs, projectsIDs, search, offset, activeTab, paymentStatusCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []string, []string, string, int, string, string) []map[string]interface{}); ok {
		r0 = rf(ctx, clientID, externalClientsIDs, projectsIDs, search, offset, activeTab, paymentStatusCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []string, []string, string, int, string, string) error); ok {
		r1 = rf(ctx, clientID, externalClientsIDs, projectsIDs, search, offset, activeTab, paymentStatusCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllInterviewsByOffsetAndActiveTab'
type MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call struct {
	*mock.Call
}

// GetAllInterviewsByOffsetAndActiveTab is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID int64
//   - externalClientsIDs []string
//   - projectsIDs []string
//   - search string
//   - offset int
//   - activeTab string
//   - paymentStatusCode string
func (_e *MockQsInterviewsRepository_Expecter) GetAllInterviewsByOffsetAndActiveTab(ctx interface{}, clientID interface{}, externalClientsIDs interface{}, projectsIDs interface{}, search interface{}, offset interface{}, activeTab interface{}, paymentStatusCode interface{}) *MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call {
	return &MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call{Call: _e.mock.On("GetAllInterviewsByOffsetAndActiveTab", ctx, clientID, externalClientsIDs, projectsIDs, search, offset, activeTab, paymentStatusCode)}
}

func (_c *MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call) Run(run func(ctx context.Context, clientID int64, externalClientsIDs []string, projectsIDs []string, search string, offset int, activeTab string, paymentStatusCode string)) *MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]string), args[3].([]string), args[4].(string), args[5].(int), args[6].(string), args[7].(string))
	})
	return _c
}

func (_c *MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call) RunAndReturn(run func(context.Context, int64, []string, []string, string, int, string, string) ([]map[string]interface{}, error)) *MockQsInterviewsRepository_GetAllInterviewsByOffsetAndActiveTab_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQsInterviewsRepository creates a new instance of MockQsInterviewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQsInterviewsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQsInterviewsRepository {
	mock := &MockQsInterviewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
